// CivSpatial Replay Viewer — vanilla TS + HTML5 canvas, no framework, no runtime deps.
// Loads the JSON emitted by `civ viewer-export` and lets you step through the questions a model
// went through: the board, the question's referents/candidates, model-vs-correct answer, and (for
// interactive encodings) the exploration trajectory. Fully offline; no LLM calls.
//
// Compiled to a single dist/viewer.js (tsconfig module:"none", outFile). No import/export here.
//
// Rendering: a pan/zoomable canvas over a "world" where each tile is TILE world-pixels. Terrain,
// cities and units are blitted from the GPL Freeciv `trident` OVERHEAD tileset when present
// (src/tileset-data.js, generated by scripts/build-tileset.mjs) and fall back to flat color when a
// sprite or the asset bundle is missing.

// ---------------------------------------------------------------------------
// JSON contract (mirrors civ-cli/src/viewer_export.rs)
// ---------------------------------------------------------------------------
interface TileD { x: number; y: number; terrain: string; extras: string[]; owner: string | null; }
// `improvements` (City Walls / Coastal Defense / Great Wall / Palace / …) is load-bearing for the
// tool playground's wall/coastal/Great-Wall/Palace math; older exports omit it (treated as none).
interface CityD { x: number; y: number; id: number; name: string; owner: string; size: number; improvements?: string[]; }
interface UnitD { x: number; y: number; id: number; kind: string; owner: string; veteran: number; hp: number; }
interface BoardContentsD { tiles: TileD[]; cities: CityD[]; units: UnitD[]; }
interface PlayerD { name: string; nation: string; }
interface BoardD extends BoardContentsD {
  source: string; width: number; height: number;
  // Fog metadata (optional; older exports omit them). `perspective` is the fogging player ("you").
  // `unfogged` is the full ground-truth board present only when this board is a fogged view.
  perspective?: string;
  unfogged?: BoardContentsD;
  // Player roster: leader `name` (the owner-identity string) -> real `nation`. Owners are LABELED by
  // nation so placeholder leader names ("Unassigned5") don't surface. Optional/backward-compatible.
  players?: PlayerD[];
}
interface PointD { kind: "tile" | "city" | "unit"; x: number; y: number; id?: number; label?: string; }
interface BBox { x0: number; y0: number; x1: number; y1: number; }
interface ToolCallD { name: string; args: string; region: BBox | null; }
interface TurnD { tool_calls: ToolCallD[]; fetched_regions: BBox[]; text: string; reasoning?: string; }
interface QuestionD {
  item_id: string; category: string; tier: string; encoding: string; board_ref: string;
  model?: string;         // run/model label (e.g. "DeepSeek", "Haiku p1") for merged multi-run bundles
  question_text: string;
  full_prompt?: string;   // the FULL turn-0 prompt (instructions + board preamble + question)
  model_answer: string;   // the PARSED answer (`result.got`); empty when scoring couldn't parse it
  answer_text?: string;   // the model's RAW completion text (shown when model_answer is empty)
  correct_answer: string; status: string;
  referents: PointD[]; candidates: PointD[]; options: string[]; radius?: number;
  reasoning?: string;     // model reasoning, when the trace carried it (static or interactive)
  trajectory?: TurnD[];
  // Aggregate per-question metrics summed over the trace's turns (added by viewer_export.rs). Present
  // on newer exports; older ones omit them (guarded at read sites). `cached_tokens` is the cache-hit
  // SUBSET of `prompt_tokens` (not additive); there is no total_tokens (total = prompt + completion).
  latency_ms?: number;
  prompt_tokens?: number; completion_tokens?: number; cached_tokens?: number;
  n_turns?: number; n_tool_calls?: number;
  tool_call_counts?: Record<string, number>; // tool name -> call count over ALL turns (all tool-using encodings)
  trace_file?: string;    // source trace filename — the unique key for the copy-identifier
}
interface ExportD {
  boards: Record<string, BoardD>;
  questions: QuestionD[];
  meta?: { trace_dir?: string; model?: string; models?: string[]; n_questions?: number; n_boards?: number };
}

// ---------------------------------------------------------------------------
// Trident tileset (optional): window.__CIVSPATIAL_TILESET__ from src/tileset-data.js.
// ---------------------------------------------------------------------------
interface SpriteRect { sheet: string; x: number; y: number; w: number; h: number; }
interface TilesetD { sheets: Record<string, string>; sprites: Record<string, SpriteRect>; }

const TILESET: TilesetD | null =
  (window as unknown as { __CIVSPATIAL_TILESET__?: TilesetD }).__CIVSPATIAL_TILESET__ ?? null;
const sheetImages: Record<string, HTMLImageElement> = {};
let spritesReady = false;
let useSprites = true; // user toggle; only has effect when a tileset is loaded

// Map OUR terrain names -> trident `graphic_str` tags (isolated, non-blended representative sprite).
// Water (Ocean/Lake/Deep Ocean) and Unknown intentionally have no sprite -> flat color fallback.
const TERRAIN_SPRITE: Record<string, string> = {
  "Grassland": "t.l0.grassland1",
  "Plains": "t.l0.plains_n0e0s0w0",
  "Forest": "t.l0.forest_n0e0s0w0",
  "Hills": "t.l0.hills_n0e0s0w0",
  "Mountains": "t.l0.mountains_n0e0s0w0",
  "Desert": "t.l0.desert_n0e0s0w0",
  "Jungle": "t.l0.jungle_n0e0s0w0",
  "Swamp": "t.l0.swamp_n0e0s0w0",
  "Tundra": "t.l0.tundra_n0e0s0w0",
  "Glacier": "t.l0.arctic_n0e0s0w0", // freeciv calls glacier "arctic"
  "Inaccessible": "t.l0.inaccessible1",
};
// Unit-kind aliases where our name differs from the freeciv tag root.
const UNIT_ALIAS: Record<string, string> = { "workers": "worker" };

function spriteRect(tag: string): SpriteRect | null {
  if (!TILESET || !spritesReady || !useSprites) return null;
  return TILESET.sprites[tag] ?? null;
}
function unitTag(kind: string): string {
  const n = kind.toLowerCase().replace(/\./g, "").replace(/\s+/g, "_");
  return `u.${UNIT_ALIAS[n] ?? n}_Idle`;
}
function cityTag(size: number): string {
  const idx = size <= 4 ? 0 : size <= 8 ? 1 : 2;
  return `city.european_city_${idx}`;
}
// Blit a sprite centered in the given world rect. Returns false if the sprite/sheet is unavailable.
function blitSprite(tag: string, x: number, y: number, w: number, h: number): boolean {
  const r = spriteRect(tag);
  if (!r) return false;
  const img = sheetImages[r.sheet];
  if (!img || !img.complete || !img.naturalWidth) return false;
  ctx.drawImage(img, r.x, r.y, r.w, r.h, x, y, w, h);
  return true;
}

// ---------------------------------------------------------------------------
// Terrain palette — mirrors the eval's own terrain names (civ-eval/src/encoders.rs).
// Used as the base fill (always drawn under terrain sprites) and as the fallback when no sprite.
// ---------------------------------------------------------------------------
const TERRAIN_COLORS: Record<string, string> = {
  "Grassland": "#6ab04c",
  "Plains": "#c8b560",
  "Forest": "#2e7d4f",
  "Hills": "#a08a5b",
  "Mountains": "#8b8178",
  "Desert": "#e2cf8a",
  "Jungle": "#3f8c3a",
  "Swamp": "#6b7d4f",
  "Tundra": "#b9c1c4",
  "Glacier": "#e8f0f4",
  "Lake": "#5fa8d3",
  "Ocean": "#3d7bb5",
  "Deep Ocean": "#26507e",
  "Inaccessible": "#3a3a3a",
  "Unknown": "#20242b",
};
function terrainColor(t: string): string { return TERRAIN_COLORS[t] ?? "#ff00ff"; }

// Owner colors are assigned by a STABLE INDEX over the set of owners actually present on the board
// (sorted for determinism), NOT by hash(name) mod N — the old hash scheme collided (e.g. "Unassigned5"
// and "Testcontroller" both landed on the same yellow). Distinct up to the palette size; only when a
// board has more owners than colors do we wrap (and the legend then shows the shared swatch honestly).
const OWNER_COLORS = ["#e15554", "#4d9de0", "#e1bc29", "#7768ae", "#3bb273",
  "#e07b39", "#d16ba5", "#5c9ead", "#b5651d", "#8a89a6"];
const OWNER_FALLBACK = "#9aa0a6"; // for an owner not in the current board's index (shouldn't happen)
let ownerColorMap: Record<string, string> = {};
let ownerOrder: string[] = []; // owners in the order they were assigned colors (for the legend)
let nationMap: Record<string, string> = {}; // owner-identity (leader name) -> real nation

// Collect every owner that appears anywhere in a board view (territory, cities, units) plus the
// perspective player, then assign palette colors by sorted index. Colors key on the stable owner
// IDENTITY (leader name); the DISPLAY label (see ownerLabel) is the nation.
function buildOwnerColors(board: BoardD) {
  nationMap = {};
  for (const p of board.players ?? []) if (p.nation) nationMap[p.name] = p.nation;
  const owners = new Set<string>();
  const addContents = (c: BoardContentsD) => {
    for (const t of c.tiles) if (t.owner) owners.add(t.owner);
    for (const ct of c.cities) owners.add(ct.owner);
    for (const u of c.units) owners.add(u.owner);
  };
  addContents(board);
  if (board.unfogged) addContents(board.unfogged);
  if (board.perspective) owners.add(board.perspective);
  ownerOrder = [...owners].sort();
  ownerColorMap = {};
  ownerOrder.forEach((name, i) => { ownerColorMap[name] = OWNER_COLORS[i % OWNER_COLORS.length]; });
}
function ownerColor(name: string): string { return ownerColorMap[name] ?? OWNER_FALLBACK; }
// The user-facing label for an owner: its nation, falling back to the leader name when the nation is
// missing/empty. This is what keeps placeholder "UnassignedN" leader names off the display.
function ownerLabel(name: string): string { return nationMap[name] || name; }

function cssVar(name: string): string {
  return getComputedStyle(document.documentElement).getPropertyValue(name).trim() || "#888";
}

// ---------------------------------------------------------------------------
// State
// ---------------------------------------------------------------------------
let DATA: ExportD | null = null;
let filtered: QuestionD[] = [];
let selectedIndex = -1;   // index into `filtered`
let stepTurn = -1;        // current interactive turn (-1 = none)
// Fog toggle: true = show what the MODEL saw (the fogged view = board's own tiles); false = full
// ground truth (board.unfogged). Only meaningful when the board carries an `unfogged` companion.
let showFog = true;

const $ = (id: string) => document.getElementById(id)!;
const canvas = $("board") as HTMLCanvasElement;
const ctx = canvas.getContext("2d")!;

// One world tile = TILE world-pixels (matches the 30px native trident sprite for crisp blits).
const TILE = 30;
// View transform: screen = world * scale + translate. Rebuilt to "fit board" on each selection.
const view = { scale: 1, tx: 0, ty: 0 };
let viewInitForBoard: string | null = null;

// ---------------------------------------------------------------------------
// Data loading
// ---------------------------------------------------------------------------
function loadData(d: ExportD) {
  DATA = d;
  const meta = d.meta || {};
  const modelBits = (meta.models && meta.models.length)
    ? ` · runs: ${meta.models.join(", ")}`
    : (meta.model ? ` · model: ${meta.model}` : "");
  $("metaLine").textContent =
    `${d.questions.length} questions · ${Object.keys(d.boards).length} board(s)` + modelBits;
  viewInitForBoard = null;
  populateFilters();
  applyFilters();
  if (filtered.length) selectQuestion(0);
  // The Stats / Compare view renders permanently below the replay layout — rebuild it against new data.
  renderStats();
}

function populateFilters() {
  if (!DATA) return;
  const cats = new Set<string>(), encs = new Set<string>(), models = new Set<string>();
  for (const q of DATA.questions) {
    cats.add(q.category); encs.add(q.encoding);
    if (q.model) models.add(q.model);
  }
  // The run/model filter only makes sense (and only appears) when the bundle mixes runs.
  const modelSel = document.getElementById("fModel") as HTMLSelectElement | null;
  if (modelSel) {
    if (models.size > 1) { fillSelect(modelSel, models, "All runs"); modelSel.hidden = false; }
    else { modelSel.hidden = true; modelSel.value = ""; }
  }
  fillSelect($("fCategory") as HTMLSelectElement, cats, "All categories");
  fillSelect($("fEncoding") as HTMLSelectElement, encs, "All encodings");
}
function fillSelect(sel: HTMLSelectElement, values: Set<string>, allLabel: string) {
  const cur = sel.value;
  sel.innerHTML = "";
  const all = document.createElement("option"); all.value = ""; all.textContent = allLabel;
  sel.appendChild(all);
  for (const v of [...values].sort()) {
    const o = document.createElement("option"); o.value = v; o.textContent = v; sel.appendChild(o);
  }
  sel.value = cur;
}

// Normalize scoring status into one of the three viewer buckets.
function statusBucket(status: string): "correct" | "wrong" | "invalid" {
  const s = status.toLowerCase();
  if (s === "correct") return "correct";
  if (s === "invalid" || s === "off-board" || s === "unparseable" || s === "refused") return "invalid";
  return "wrong";
}

// Filter the loaded question set by category / encoding / result. Shared by the replay list and the
// Stats / Compare view (item 7) so both honor exactly the same filter logic. Empty string = "all".
function filterQuestions(fc: string, fe: string, fs: string, fm = ""): QuestionD[] {
  if (!DATA) return [];
  return DATA.questions.filter(q =>
    (!fc || q.category === fc) && (!fe || q.encoding === fe) &&
    (!fs || statusBucket(q.status) === fs) && (!fm || q.model === fm));
}

function applyFilters() {
  if (!DATA) return;
  const modelSel = document.getElementById("fModel") as HTMLSelectElement | null;
  filtered = filterQuestions(
    ($("fCategory") as HTMLSelectElement).value,
    ($("fEncoding") as HTMLSelectElement).value,
    ($("fStatus") as HTMLSelectElement).value,
    modelSel && !modelSel.hidden ? modelSel.value : "");
  renderList();
  if (selectedIndex >= filtered.length) selectedIndex = filtered.length - 1;
}

// ---------------------------------------------------------------------------
// Question list (grouped by category × encoding)
// ---------------------------------------------------------------------------
function renderList() {
  const host = $("qlist"); host.innerHTML = "";
  if (!filtered.length) { host.innerHTML = `<div class="empty">No questions match.</div>`; return; }
  const groups = new Map<string, QuestionD[]>();
  for (const q of filtered) {
    const key = (q.model ? `${q.model} · ` : "") + `${q.category} · ${q.encoding}`;
    (groups.get(key) ?? groups.set(key, []).get(key)!).push(q);
  }
  for (const [key, qs] of groups) {
    const h = document.createElement("div"); h.className = "qgroup-h";
    const nPass = qs.filter(q => statusBucket(q.status) === "correct").length;
    h.textContent = `${key}  (${nPass}/${qs.length} correct)`;
    host.appendChild(h);
    for (const q of qs) {
      const idx = filtered.indexOf(q);
      const row = document.createElement("div");
      row.className = "qitem" + (idx === selectedIndex ? " active" : "");
      const bucket = statusBucket(q.status);
      row.innerHTML =
        `<span class="qid">${escapeHtml(shortId(q.item_id))}</span>` +
        `<span class="badge ${bucket}">${bucket === "correct" ? "PASS" : bucket === "wrong" ? "FAIL" : "INV"}</span>`;
      row.title = q.item_id;
      row.onclick = () => selectQuestion(idx);
      host.appendChild(row);
    }
  }
}
function shortId(id: string): string {
  const c = id.indexOf(":");
  return c >= 0 ? id.slice(c + 1) : id;
}
function escapeHtml(s: string): string {
  return s.replace(/[&<>"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]!));
}

// ---------------------------------------------------------------------------
// Selection
// ---------------------------------------------------------------------------
function selectQuestion(idx: number) {
  if (idx < 0 || idx >= filtered.length) return;
  selectedIndex = idx;
  const q = filtered[idx];
  stepTurn = q.trajectory && q.trajectory.length ? 0 : -1;
  renderList();
  renderAnswer(q);
  renderStepper(q);
  updateFogBtn();
  updateCenterTitle(q);
  refreshToolPlayerDefaults();
  updatePickHint();
  drawBoard();
  ($("prevBtn") as HTMLButtonElement).disabled = idx <= 0;
  ($("nextBtn") as HTMLButtonElement).disabled = idx >= filtered.length - 1;
}

function currentQuestion(): QuestionD | null {
  return selectedIndex >= 0 && selectedIndex < filtered.length ? filtered[selectedIndex] : null;
}
function currentBoard(): BoardD | null {
  const q = currentQuestion();
  if (!q || !DATA) return null;
  return DATA.boards[q.board_ref] ?? null;
}
// Whether the current board can toggle fog (i.e. carries a distinct ground-truth companion).
function boardHasFog(board: BoardD | null): boolean { return !!(board && board.unfogged); }
// The tiles/cities/units to actually render: the fogged (as-seen) view unless fog is toggled off and
// a ground-truth companion exists. Backward compatible: boards without `unfogged` always render as-is.
function currentView(board: BoardD): BoardContentsD {
  return (!showFog && board.unfogged) ? board.unfogged : board;
}

// ---------------------------------------------------------------------------
// Answer panel — Priority 1: show the MODEL'S answer prominently alongside the correct one.
// ---------------------------------------------------------------------------
function renderAnswer(q: QuestionD) {
  const bucket = statusBucket(q.status);
  const el = $("answer");
  el.innerHTML = "";

  // Pass/fail chip.
  const pill = document.createElement("div");
  pill.className = `pill ${bucket}`;
  pill.textContent = bucket === "correct" ? "CORRECT" : bucket === "wrong" ? "WRONG" : q.status.toUpperCase();
  el.appendChild(pill);

  // The headline: model answer vs correct answer, side by side.
  const modelParsed = q.model_answer && q.model_answer.trim();
  const cmp = document.createElement("div");
  cmp.className = "answercmp";
  cmp.appendChild(bigAnswer("Model answered", modelParsed ? q.model_answer : "(unparseable)", bucket, !modelParsed));
  cmp.appendChild(bigAnswer("Correct answer", q.correct_answer || "—", "correct", false));
  el.appendChild(cmp);

  // Metadata rows.
  const modelName = q.model || (DATA && DATA.meta && DATA.meta.model) || "";
  if (modelName) el.appendChild(kv(q.model ? "Run" : "Model", modelName));
  el.appendChild(kv("Category", `${q.category}  (${q.tier})`));
  el.appendChild(kv("Encoding", q.encoding));
  if (q.options && q.options.length) el.appendChild(kv("Options", q.options.join(" | ")));

  // Latency + token + turn/tool-call metrics (summed over the trace's turns), when the export carries
  // them. cached is the cache-hit SUBSET of prompt (shown as "X cached", never added into a total).
  const m = metricsBlock(q); if (m) el.appendChild(m);

  // Collapsible sections (item 2), same treatment as the full prompt. The question moved here from the
  // board window; it stays open by default (open once its board eats less vertical space). The model's
  // raw answer text and the reasoning are collapsed by default so they don't dominate.
  const qtext = (q.question_text || "").trim(); // some exports carry a leading "\n\nQUESTION:" gap
  if (qtext) el.appendChild(collapsible("Question", qtext, { open: true }));

  // The model's raw completion text — the ONLY place the answer survives when parsing failed
  // (status=invalid). This is the field the previous build dropped.
  if (q.answer_text && q.answer_text.trim())
    el.appendChild(collapsible("Model's answer text", q.answer_text, { mono: true }));

  // Reasoning: explicit trace reasoning, else the last trajectory turn's `.reasoning` (item 4 fix —
  // no longer the turn's answer text). Omitted entirely when the trace carried no reasoning.
  const reasoning = q.reasoning && q.reasoning.trim() ? q.reasoning : lastReasoning(q);
  if (reasoning) el.appendChild(collapsible("Reasoning", reasoning, { muted: true }));

  // Full prompt / system — the entire turn-0 prompt (instructions + board preamble + question),
  // collapsed by default so it doesn't dominate. (Intentionally left untrimmed.)
  if (q.full_prompt && q.full_prompt.trim())
    el.appendChild(collapsible(`Full prompt / system  (${q.full_prompt.length.toLocaleString()} chars)`, q.full_prompt, { mono: true }));
}
// A collapsible <details> section — the shared "same treatment the full prompt already has" (item 2).
function collapsible(label: string, text: string, opts: { open?: boolean; mono?: boolean; muted?: boolean } = {}): HTMLElement {
  const det = document.createElement("details"); det.className = "collapse";
  if (opts.open) det.open = true;
  const sum = document.createElement("summary"); sum.textContent = label;
  const body = document.createElement("div");
  body.className = "collapsebody" + (opts.mono ? " mono" : "") + (opts.muted ? " muted" : "");
  body.textContent = text;
  det.appendChild(sum); det.appendChild(body);
  return det;
}
// A large, prominent answer block (model vs correct).
function bigAnswer(label: string, value: string, tone: "correct" | "wrong" | "invalid", muted: boolean): HTMLElement {
  const box = document.createElement("div");
  box.className = `bigans ${tone}` + (muted ? " muted" : "");
  const l = document.createElement("div"); l.className = "l"; l.textContent = label;
  const v = document.createElement("div"); v.className = "v"; v.textContent = value;
  box.appendChild(l); box.appendChild(v);
  return box;
}
function kv(k: string, v: string): HTMLElement {
  const row = document.createElement("div"); row.className = "ansrow";
  row.innerHTML = `<span class="k">${escapeHtml(k)}</span><span class="v">${escapeHtml(v)}</span>`;
  return row;
}
// A small grid of stat tiles: latency, tokens, cached, turns/tool-calls. Returns null when the export
// carries none of the aggregate metrics (older exports).
function metricsBlock(q: QuestionD): HTMLElement | null {
  const has = q.latency_ms != null || q.prompt_tokens != null || q.completion_tokens != null ||
    q.n_turns != null || q.n_tool_calls != null;
  if (!has) return null;
  const wrap = document.createElement("div"); wrap.className = "metrics";
  const cell = (label: string, value: string, sub?: string) => {
    const c = document.createElement("div"); c.className = "metric";
    const l = document.createElement("div"); l.className = "ml"; l.textContent = label;
    const v = document.createElement("div"); v.className = "mv"; v.textContent = value;
    c.appendChild(l); c.appendChild(v);
    if (sub) { const s = document.createElement("div"); s.className = "ms"; s.textContent = sub; c.appendChild(s); }
    wrap.appendChild(c);
  };
  if (q.latency_ms != null) {
    const ms = q.latency_ms;
    cell("Latency", ms >= 1000 ? (ms / 1000).toFixed(2) + " s" : ms + " ms", ms >= 1000 ? `${ms.toLocaleString()} ms` : undefined);
  }
  if (q.prompt_tokens != null || q.completion_tokens != null) {
    const p = q.prompt_tokens ?? 0, c = q.completion_tokens ?? 0;
    cell("Tokens", (p + c).toLocaleString(), `${p.toLocaleString()} prompt + ${c.toLocaleString()} completion`);
  }
  if (q.cached_tokens != null) cell("Cached", q.cached_tokens.toLocaleString(), "of prompt (cache hit)");
  if (q.n_turns != null || q.n_tool_calls != null) cell("Turns", String(q.n_turns ?? 0), `${q.n_tool_calls ?? 0} tool calls`);
  return wrap;
}
// The last GENUINE reasoning a trajectory carried. Item 4: this used to fall back to a turn's
// assistant `.text`, but that text IS the model's answer (viewer_export.rs sets `answer_text` to the
// final turn's text), so "Reasoning" rendered a verbatim copy of "Model's answer text". Reasoning now
// surfaces only real reasoning (`q.reasoning` or a turn's `.reasoning`); when a trace carries none, the
// section is simply omitted rather than echoing the answer.
function lastReasoning(q: QuestionD): string {
  if (!q.trajectory || !q.trajectory.length) return "";
  for (let i = q.trajectory.length - 1; i >= 0; i--) {
    const t = q.trajectory[i];
    if (t.reasoning) return t.reasoning;
  }
  return "";
}

// ---------------------------------------------------------------------------
// Interactive stepper
// ---------------------------------------------------------------------------
function renderStepper(q: QuestionD) {
  const wrap = $("stepper");
  if (!q.trajectory || !q.trajectory.length) { wrap.classList.remove("on"); return; }
  wrap.classList.add("on");
  updateStepperBody();
}
function updateStepperBody() {
  const q = currentQuestion();
  if (!q || !q.trajectory) return;
  const n = q.trajectory.length;
  $("turnLbl").textContent = `Turn ${stepTurn + 1} / ${n}`;
  ($("stepPrev") as HTMLButtonElement).disabled = stepTurn <= 0;
  ($("stepNext") as HTMLButtonElement).disabled = stepTurn >= n - 1;
  const turn = q.trajectory[Math.max(0, stepTurn)];
  $("turnText").textContent = turn.text || (turn.reasoning ? "" : "(no assistant text this turn)");
  const calls = $("turnCalls"); calls.innerHTML = "";
  for (const c of turn.tool_calls) {
    const div = document.createElement("div"); div.className = "toolcall";
    const reg = c.region ? ` <span class="fetch">↳ fetch (${c.region.x0},${c.region.y0})–(${c.region.x1},${c.region.y1})</span>` : "";
    div.innerHTML = `${escapeHtml(c.name)}(${escapeHtml(c.args)})${reg}`;
    calls.appendChild(div);
  }
  if (!turn.tool_calls.length) {
    const div = document.createElement("div"); div.className = "toolcall"; div.textContent = "(final answer — no tool calls)";
    calls.appendChild(div);
  }
  drawBoard();
}

// ---------------------------------------------------------------------------
// View transform helpers (Priority 2: zoom + pan)
// ---------------------------------------------------------------------------
function sizeCanvas() {
  const wrap = canvas.parentElement as HTMLElement | null;
  const cw = wrap && wrap.clientWidth ? wrap.clientWidth - 24 : 900;
  canvas.width = Math.max(320, Math.floor(cw));
  canvas.height = 520; // trimmed a little (was 600) to reclaim vertical space (item 2)
}
// Fit the whole board into the canvas with a small margin (the default, screenshot-friendly zoom).
function fitView(board: BoardD) {
  sizeCanvas();
  const pad = 14;
  const s = Math.min(
    (canvas.width - pad * 2) / (board.width * TILE),
    (canvas.height - pad * 2) / (board.height * TILE),
  );
  view.scale = s > 0 ? s : 1;
  view.tx = (canvas.width - board.width * TILE * view.scale) / 2;
  view.ty = (canvas.height - board.height * TILE * view.scale) / 2;
}
function clampScale(s: number): number { return Math.max(0.05, Math.min(24, s)); }
// Screen (backing-store) pixel -> world coordinate.
function screenToWorld(sx: number, sy: number): { x: number; y: number } {
  return { x: (sx - view.tx) / view.scale, y: (sy - view.ty) / view.scale };
}
// Mouse event -> backing-store pixel (accounts for CSS scaling of the canvas).
function eventToScreen(e: MouseEvent): { x: number; y: number } {
  const rect = canvas.getBoundingClientRect();
  const kx = canvas.width / (rect.width || canvas.width);
  const ky = canvas.height / (rect.height || canvas.height);
  return { x: (e.clientX - rect.left) * kx, y: (e.clientY - rect.top) * ky };
}

// ---------------------------------------------------------------------------
// Canvas rendering
// ---------------------------------------------------------------------------
function drawBoard() {
  const board = currentBoard();
  const q = currentQuestion();
  ctx.setTransform(1, 0, 0, 1, 0, 0);
  ctx.clearRect(0, 0, canvas.width, canvas.height);
  if (!board) return;

  // Initialize/fit the view when the board changes.
  if (viewInitForBoard !== board.source) { fitView(board); buildOwnerColors(board); viewInitForBoard = board.source; }

  const vw = currentView(board);
  ctx.imageSmoothingEnabled = false;
  ctx.setTransform(view.scale, 0, 0, view.scale, view.tx, view.ty);
  const px = 1 / view.scale; // one screen pixel expressed in world units (screen-constant outlines)

  // Terrain: flat color base (also the fallback / water), then a sprite blit on top when available.
  for (const t of vw.tiles) {
    const wx = t.x * TILE, wy = t.y * TILE;
    ctx.fillStyle = terrainColor(t.terrain);
    ctx.fillRect(wx, wy, TILE, TILE);
    const tag = TERRAIN_SPRITE[t.terrain];
    if (tag) blitSprite(tag, wx, wy, TILE, TILE);
  }
  // Territory tint (owner-colored inset) + infrastructure markers.
  for (const t of vw.tiles) {
    const wx = t.x * TILE, wy = t.y * TILE;
    if (t.owner) {
      ctx.strokeStyle = ownerColor(t.owner);
      ctx.globalAlpha = 0.55; ctx.lineWidth = 2 * px;
      ctx.strokeRect(wx + px, wy + px, TILE - 2 * px, TILE - 2 * px);
      ctx.globalAlpha = 1;
    }
    drawExtras(t, wx, wy);
  }
  // Subtle grid when zoomed in enough to matter.
  if (view.scale * TILE >= 16) {
    ctx.strokeStyle = "rgba(0,0,0,.14)"; ctx.lineWidth = px;
    for (let x = 0; x <= board.width; x++) { ctx.beginPath(); ctx.moveTo(x * TILE, 0); ctx.lineTo(x * TILE, board.height * TILE); ctx.stroke(); }
    for (let y = 0; y <= board.height; y++) { ctx.beginPath(); ctx.moveTo(0, y * TILE); ctx.lineTo(board.width * TILE, y * TILE); ctx.stroke(); }
  }

  // Interactive: fetched-region overlays up to the current step.
  if (q && q.trajectory && stepTurn >= 0) drawFetched(q, px);

  // Cities & units — distinctly larger, owner-colored, outlined so they pop.
  for (const c of vw.cities) drawCity(c, px);
  for (const u of vw.units) drawUnit(u, px);

  // Question highlights (referents/candidates/work radius).
  if (q) drawHighlights(q, px);

  // Coordinate ruler along the top/left edges (item 6) — drawn in screen space so it stays crisp and
  // unscaled under any zoom/pan.
  drawCoordLabels(board);

  renderLegend(board);
}

// Row/column coordinate labels along the board's top and left edges (item 6). Drawn in screen space
// (identity transform) inside translucent gutters, at PERIODIC ticks whose spacing grows with zoom-out
// so 2–3 digit numbers never collide.
function drawCoordLabels(board: BoardD) {
  ctx.setTransform(1, 0, 0, 1, 0, 0);
  const cell = TILE * view.scale;              // screen px per tile
  if (cell <= 0) return;
  const topGut = 15, leftGut = 22;             // leftGut wider to seat 3-digit row numbers
  // Visible tile range (clamp to the board).
  const wl = screenToWorld(leftGut, topGut), wr = screenToWorld(canvas.width, canvas.height);
  const x0 = Math.max(0, Math.floor(wl.x / TILE)), x1 = Math.min(board.width - 1, Math.ceil(wr.x / TILE));
  const y0 = Math.max(0, Math.floor(wl.y / TILE)), y1 = Math.min(board.height - 1, Math.ceil(wr.y / TILE));
  if (x1 < x0 || y1 < y0) return;
  const step = Math.max(1, Math.ceil(30 / cell)); // ~30px minimum between labels
  // Translucent gutters so numbers read over any terrain.
  ctx.globalAlpha = 0.82; ctx.fillStyle = cssVar("--panel");
  ctx.fillRect(0, 0, canvas.width, topGut);
  ctx.fillRect(0, 0, leftGut, canvas.height);
  ctx.globalAlpha = 1;
  ctx.fillStyle = cssVar("--muted");
  ctx.font = "10px ui-monospace, Menlo, Consolas, monospace";
  ctx.textBaseline = "middle";
  // Columns along the top.
  ctx.textAlign = "center";
  for (let x = Math.ceil(x0 / step) * step; x <= x1; x += step) {
    const sx = view.tx + (x + 0.5) * TILE * view.scale;
    if (sx <= leftGut + 4 || sx >= canvas.width - 2) continue;
    ctx.fillText(String(x), sx, topGut / 2);
  }
  // Rows along the left.
  for (let y = Math.ceil(y0 / step) * step; y <= y1; y += step) {
    const sy = view.ty + (y + 0.5) * TILE * view.scale;
    if (sy <= topGut + 4 || sy >= canvas.height - 2) continue;
    ctx.fillText(String(y), leftGut / 2, sy);
  }
}

function drawExtras(t: TileD, px: number, py: number) {
  const has = (e: string) => t.extras.includes(e);
  if (has("River")) {
    ctx.strokeStyle = "#3aa0ff"; ctx.lineWidth = Math.max(1, TILE / 8);
    ctx.beginPath(); ctx.moveTo(px + TILE * 0.2, py); ctx.lineTo(px + TILE * 0.6, py + TILE); ctx.stroke();
  }
  if (has("Railroad")) {
    ctx.strokeStyle = "#111"; ctx.lineWidth = Math.max(1, TILE / 9);
    ctx.beginPath(); ctx.moveTo(px, py + TILE / 2); ctx.lineTo(px + TILE, py + TILE / 2); ctx.stroke();
  } else if (has("Road")) {
    ctx.strokeStyle = "#6b5b3e"; ctx.lineWidth = Math.max(1, TILE / 12);
    ctx.beginPath(); ctx.moveTo(px, py + TILE / 2); ctx.lineTo(px + TILE, py + TILE / 2); ctx.stroke();
  }
  // A resource / special extra dot (anything that isn't infrastructure/terrain feature).
  const infra = new Set(["River", "Road", "Railroad", "Irrigation", "Mine", "Farmland", "Fortress", "Airbase", "Pollution", "Fallout", "Hut"]);
  if (t.extras.some(e => !infra.has(e))) {
    ctx.fillStyle = "#fff"; ctx.strokeStyle = "#b8860b"; ctx.lineWidth = 1;
    ctx.beginPath(); ctx.arc(px + TILE * 0.78, py + TILE * 0.22, TILE / 7, 0, Math.PI * 2);
    ctx.fill(); ctx.stroke();
  }
}

// A bold, legible owner ring drawn ON TOP of a sprite: a dark backing stroke plus the owner color,
// so it reads on any terrain and isn't hidden under the sprite art.
function ownerRing(wx: number, wy: number, oc: string, px: number) {
  const x = wx + 1.75 * px, y = wy + 1.75 * px, w = TILE - 3.5 * px, h = TILE - 3.5 * px;
  ctx.strokeStyle = "rgba(0,0,0,.7)"; ctx.lineWidth = 4 * px; ctx.strokeRect(x, y, w, h);
  ctx.strokeStyle = oc; ctx.lineWidth = 2.5 * px; ctx.strokeRect(x, y, w, h);
}

function drawCity(c: CityD, px: number) {
  const wx = c.x * TILE, wy = c.y * TILE;
  const oc = ownerColor(c.owner);
  if (!blitSprite(cityTag(c.size), wx, wy, TILE, TILE)) {
    // Fallback: a filled owner-colored diamond with white outline.
    const cx = wx + TILE / 2, cy = wy + TILE / 2, r = TILE * 0.42;
    ctx.fillStyle = oc; ctx.strokeStyle = "#fff"; ctx.lineWidth = 2 * px;
    ctx.beginPath();
    ctx.moveTo(cx, cy - r); ctx.lineTo(cx + r, cy); ctx.lineTo(cx, cy + r); ctx.lineTo(cx - r, cy); ctx.closePath();
    ctx.fill(); ctx.stroke();
  }
  // Bold owner ring ON TOP so the city's owner reads even under the sprite.
  ownerRing(wx, wy, oc, px);
  // Size badge bottom-right + optional name label at higher zoom.
  drawBadge(String(c.size), wx + TILE, wy + TILE, oc, px, "br");
  if (view.scale >= 1.1 && c.name) drawLabel(c.name, wx + TILE / 2, wy - 2 * px, px);
}

function drawUnit(u: UnitD, px: number) {
  const wx = u.x * TILE, wy = u.y * TILE;
  const oc = ownerColor(u.owner);
  // Owner-colored rounded chip behind the sprite so units pop; sprite (or a fallback marker) on top.
  const inset = TILE * 0.14;
  ctx.fillStyle = oc; ctx.globalAlpha = 0.9;
  roundRect(wx + inset, wy + inset, TILE - 2 * inset, TILE - 2 * inset, 4 * px);
  ctx.fill(); ctx.globalAlpha = 1;
  ctx.strokeStyle = "rgba(0,0,0,.65)"; ctx.lineWidth = 1.5 * px; ctx.stroke();
  if (!blitSprite(unitTag(u.kind), wx, wy, TILE, TILE)) {
    const cx = wx + TILE / 2, cy = wy + TILE / 2, r = TILE * 0.3;
    ctx.fillStyle = "#fff"; ctx.strokeStyle = oc; ctx.lineWidth = 2 * px;
    ctx.beginPath(); ctx.arc(cx, cy, r, 0, Math.PI * 2); ctx.fill(); ctx.stroke();
  }
  // Bold owner ring ON TOP so the unit's owner reads even under the sprite.
  ownerRing(wx, wy, oc, px);
}

function roundRect(x: number, y: number, w: number, h: number, r: number) {
  ctx.beginPath();
  ctx.moveTo(x + r, y);
  ctx.arcTo(x + w, y, x + w, y + h, r);
  ctx.arcTo(x + w, y + h, x, y + h, r);
  ctx.arcTo(x, y + h, x, y, r);
  ctx.arcTo(x, y, x + w, y, r);
  ctx.closePath();
}
// A small filled badge with text (e.g. city size). Anchored at a tile corner.
function drawBadge(text: string, ax: number, ay: number, color: string, px: number, _anchor: "br") {
  const s = 11 * px;
  const cx = ax - s, cy = ay - s;
  ctx.fillStyle = color; ctx.strokeStyle = "#fff"; ctx.lineWidth = 1.5 * px;
  ctx.beginPath(); ctx.arc(cx, cy, s, 0, Math.PI * 2); ctx.fill(); ctx.stroke();
  ctx.fillStyle = "#fff"; ctx.font = `${Math.round(13 * px)}px sans-serif`;
  ctx.textAlign = "center"; ctx.textBaseline = "middle";
  ctx.fillText(text, cx, cy + 0.5 * px);
}
// A small numbered badge anchored at a tile's top-left corner (candidate index). Dark disc + light
// text so it stays legible over the cyan candidate fill and any terrain.
function drawIndexBadge(text: string, tx: number, ty: number, ring: string, px: number) {
  const s = 8.5 * px, cx = tx + s + 1.5 * px, cy = ty + s + 1.5 * px;
  ctx.fillStyle = "rgba(0,0,0,.82)"; ctx.strokeStyle = ring; ctx.lineWidth = 1.75 * px;
  ctx.beginPath(); ctx.arc(cx, cy, s, 0, Math.PI * 2); ctx.fill(); ctx.stroke();
  ctx.fillStyle = "#fff"; ctx.font = `700 ${Math.round(11 * px)}px sans-serif`;
  ctx.textAlign = "center"; ctx.textBaseline = "middle";
  ctx.fillText(text, cx, cy + 0.5 * px);
}
// A short label with a readable pill behind it (drawn only when zoomed in).
function drawLabel(text: string, cx: number, baseY: number, px: number) {
  ctx.font = `${Math.round(12 * px)}px system-ui, sans-serif`;
  ctx.textAlign = "center"; ctx.textBaseline = "bottom";
  const w = ctx.measureText(text).width + 6 * px, h = 15 * px;
  ctx.fillStyle = "rgba(0,0,0,.62)";
  roundRect(cx - w / 2, baseY - h, w, h, 3 * px); ctx.fill();
  ctx.fillStyle = "#fff"; ctx.fillText(text, cx, baseY - 2 * px);
}

function drawFetched(q: QuestionD, px: number) {
  const traj = q.trajectory!;
  for (let i = 0; i <= stepTurn && i < traj.length; i++) {
    const isCurrent = i === stepTurn;
    for (const b of traj[i].fetched_regions) {
      ctx.fillStyle = cssVar("--fetch");
      ctx.globalAlpha = isCurrent ? 0.34 : 0.14;
      ctx.fillRect(b.x0 * TILE, b.y0 * TILE, (b.x1 - b.x0 + 1) * TILE, (b.y1 - b.y0 + 1) * TILE);
      ctx.globalAlpha = 1;
      if (isCurrent) {
        ctx.strokeStyle = cssVar("--fetch"); ctx.lineWidth = 2.5 * px;
        ctx.strokeRect(b.x0 * TILE + px, b.y0 * TILE + px, (b.x1 - b.x0 + 1) * TILE - 2 * px, (b.y1 - b.y0 + 1) * TILE - 2 * px);
      }
    }
  }
}

function drawHighlights(q: QuestionD, px: number) {
  // Work-radius rings (region-count / best-site) around referents/candidates.
  if (q.radius != null) {
    const centers = q.referents.length ? q.referents : q.candidates;
    ctx.strokeStyle = cssVar("--cand"); ctx.lineWidth = 2 * px; ctx.globalAlpha = 0.7;
    for (const p of centers) {
      const x0 = (p.x - q.radius) * TILE, y0 = (p.y - q.radius) * TILE;
      const side = (2 * q.radius + 1) * TILE;
      ctx.strokeRect(x0 + px, y0 + px, side - 2 * px, side - 2 * px);
    }
    ctx.globalAlpha = 1;
  }
  // Candidates: translucent cyan fill + outline, each stamped with its 1-based index. The number is
  // the candidate's position in the option list the model chose from (see the "candidate #" legend).
  q.candidates.forEach((p, i) => {
    ctx.fillStyle = cssVar("--cand"); ctx.globalAlpha = 0.3;
    ctx.fillRect(p.x * TILE, p.y * TILE, TILE, TILE);
    ctx.globalAlpha = 1;
    ctx.strokeStyle = cssVar("--cand"); ctx.lineWidth = 3 * px;
    ctx.strokeRect(p.x * TILE + 1.5 * px, p.y * TILE + 1.5 * px, TILE - 3 * px, TILE - 3 * px);
    // Index badge anchored top-LEFT (city size sits bottom-right, resource dot top-right).
    drawIndexBadge(String(i + 1), p.x * TILE, p.y * TILE, cssVar("--cand"), px);
  });
  // Referents: bright amber ring + corner crosshair so they're findable at any zoom.
  for (const p of q.referents) {
    ctx.strokeStyle = cssVar("--ref"); ctx.lineWidth = 3.5 * px;
    ctx.strokeRect(p.x * TILE + 1.5 * px, p.y * TILE + 1.5 * px, TILE - 3 * px, TILE - 3 * px);
    const cx = p.x * TILE + TILE / 2, cy = p.y * TILE + TILE / 2, r = TILE * 0.9;
    ctx.beginPath(); ctx.moveTo(cx - r, cy); ctx.lineTo(cx - TILE * 0.35, cy);
    ctx.moveTo(cx + TILE * 0.35, cy); ctx.lineTo(cx + r, cy);
    ctx.moveTo(cx, cy - r); ctx.lineTo(cx, cy - TILE * 0.35);
    ctx.moveTo(cx, cy + TILE * 0.35); ctx.lineTo(cx, cy + r); ctx.stroke();
  }
}

function renderLegend(board: BoardD) {
  const vw = currentView(board);
  const present = new Set(vw.tiles.map(t => t.terrain));
  // Faction colors first (rendered into #ownerLegend, which sits ABOVE #legend in the DOM).
  renderOwnerLegend(board);
  const host = $("legend"); host.innerHTML = "";
  // Then the most-important markers: referent / candidate / fetched-region (item 3).
  host.appendChild(swatch(cssVar("--ref"), "referent", true));
  host.appendChild(swatch(cssVar("--cand"), "candidate", true));
  host.appendChild(markerLegend("candidate # = option index (top-left)"));
  const q = currentQuestion();
  if (q && q.trajectory) host.appendChild(swatch(cssVar("--fetch"), "fetched region", true));
  host.appendChild(markerLegend("size # = city population (bottom-right)"));
  // Terrain swatches last. (The City/Unit rows are gone — they're drawn as sprites, so the rows were
  // useless — item 3.)
  for (const name of Object.keys(TERRAIN_COLORS)) {
    if (!present.has(name)) continue;
    host.appendChild(swatch(terrainColor(name), name));
  }
}
function swatch(color: string, label: string, outline = false): HTMLElement {
  const s = document.createElement("span"); s.className = "sw";
  const chip = document.createElement("span"); chip.className = "chip";
  if (outline) { chip.style.background = "transparent"; chip.style.border = `2px solid ${color}`; }
  else chip.style.background = color;
  s.appendChild(chip); s.appendChild(document.createTextNode(label));
  return s;
}
function markerLegend(text: string): HTMLElement {
  const s = document.createElement("span"); s.className = "sw"; s.textContent = text; return s;
}

// Owner legend: swatch -> player name (the color used for that player's cities/units/territory ring),
// in the same stable order as the color assignment. The perspective player ("you") is flagged.
function renderOwnerLegend(board: BoardD) {
  const host = $("ownerLegend"); if (!host) return;
  host.innerHTML = "";
  if (!ownerOrder.length) { host.appendChild(markerLegend("(no owned tiles/objects)")); return; }
  const you = board.perspective;
  for (const name of ownerOrder) {
    const isYou = !!you && name === you;
    const s = document.createElement("span");
    s.className = "sw owner" + (isYou ? " you" : "");
    const chip = document.createElement("span"); chip.className = "chip";
    chip.style.background = ownerColorMap[name]; chip.style.borderColor = "rgba(0,0,0,.55)";
    s.appendChild(chip);
    // Label by nation; keep the (deduped) leader name as a small secondary when it differs.
    const nation = ownerLabel(name);
    let text = nation + (isYou ? "  (you)" : "");
    if (nation !== name) text += `  ·  ${name}`;
    s.appendChild(document.createTextNode(text));
    host.appendChild(s);
  }
}

// ---------------------------------------------------------------------------
// Hover readout (kept working under zoom/pan) + zoom + pan interactions
// ---------------------------------------------------------------------------
let dragging = false;
let dragMoved = false; // set when a drag actually pans, so the trailing click doesn't "pick a tile"
let dragLast = { x: 0, y: 0 };

canvas.addEventListener("mousemove", (e) => {
  const board = currentBoard(); if (!board) return;
  const sp = eventToScreen(e);
  if (dragging) {
    view.tx += sp.x - dragLast.x; view.ty += sp.y - dragLast.y;
    dragMoved = true;
    dragLast = sp; drawBoard(); return;
  }
  const w = screenToWorld(sp.x, sp.y);
  const x = Math.floor(w.x / TILE), y = Math.floor(w.y / TILE);
  if (x < 0 || y < 0 || x >= board.width || y >= board.height) { $("hover").textContent = ""; return; }
  const vw = currentView(board);
  const t = vw.tiles[y * board.width + x];
  const parts = [`(${x}, ${y}) ${t ? t.terrain : "?"}`];
  if (t && t.extras.length) parts.push(`[${t.extras.join(", ")}]`);
  if (t && t.owner) parts.push(`<${ownerLabel(t.owner)}>`);
  const city = vw.cities.find(c => c.x === x && c.y === y);
  if (city) parts.push(`city "${city.name}" size ${city.size} (${ownerLabel(city.owner)})`);
  const units = vw.units.filter(u => u.x === x && u.y === y);
  for (const u of units) parts.push(`unit ${u.kind} (${ownerLabel(u.owner)})`);
  $("hover").textContent = parts.join("  ");
});
canvas.addEventListener("mouseleave", () => { $("hover").textContent = ""; dragging = false; canvas.style.cursor = "grab"; });
canvas.addEventListener("mousedown", (e) => { dragging = true; dragMoved = false; dragLast = eventToScreen(e); canvas.style.cursor = "grabbing"; e.preventDefault(); });
// Pick-from-map for the tool playground: a genuine click (no pan) fills the focused tool field.
canvas.addEventListener("click", (e) => {
  if (dragMoved) { dragMoved = false; return; } // was a pan, not a pick
  const board = currentBoard(); if (!board) return;
  const sp = eventToScreen(e);
  const w = screenToWorld(sp.x, sp.y);
  const x = Math.floor(w.x / TILE), y = Math.floor(w.y / TILE);
  if (x < 0 || y < 0 || x >= board.width || y >= board.height) return;
  toolsPickTile(x, y, board);
});
window.addEventListener("mouseup", () => { if (dragging) { dragging = false; canvas.style.cursor = "grab"; } });
canvas.addEventListener("wheel", (e) => {
  if (!currentBoard()) return;
  e.preventDefault();
  const sp = eventToScreen(e);
  const before = screenToWorld(sp.x, sp.y);
  const factor = Math.exp(-e.deltaY * 0.0015);
  view.scale = clampScale(view.scale * factor);
  // Keep the world point under the cursor pinned.
  view.tx = sp.x - before.x * view.scale;
  view.ty = sp.y - before.y * view.scale;
  drawBoard();
}, { passive: false });

// ---------------------------------------------------------------------------
// Wiring
// ---------------------------------------------------------------------------
$("fCategory").addEventListener("change", () => { applyFilters(); if (filtered.length) selectQuestion(0); });
$("fEncoding").addEventListener("change", () => { applyFilters(); if (filtered.length) selectQuestion(0); });
$("fStatus").addEventListener("change", () => { applyFilters(); if (filtered.length) selectQuestion(0); });
{
  const fm = document.getElementById("fModel");
  if (fm) fm.addEventListener("change", () => { applyFilters(); if (filtered.length) selectQuestion(0); });
}
$("prevBtn").addEventListener("click", () => selectQuestion(selectedIndex - 1));
$("nextBtn").addEventListener("click", () => selectQuestion(selectedIndex + 1));
$("stepPrev").addEventListener("click", () => { if (stepTurn > 0) { stepTurn--; updateStepperBody(); } });
$("stepNext").addEventListener("click", () => {
  const q = currentQuestion();
  if (q && q.trajectory && stepTurn < q.trajectory.length - 1) { stepTurn++; updateStepperBody(); }
});
$("fitBtn").addEventListener("click", () => { const b = currentBoard(); if (b) { fitView(b); drawBoard(); } });
$("zoomIn").addEventListener("click", () => zoomCenter(1.3));
$("zoomOut").addEventListener("click", () => zoomCenter(1 / 1.3));
function zoomCenter(factor: number) {
  if (!currentBoard()) return;
  const cx = canvas.width / 2, cy = canvas.height / 2;
  const before = screenToWorld(cx, cy);
  view.scale = clampScale(view.scale * factor);
  view.tx = cx - before.x * view.scale;
  view.ty = cy - before.y * view.scale;
  drawBoard();
}
const spriteBtn = document.getElementById("spriteBtn");
if (spriteBtn) {
  if (!TILESET) spriteBtn.setAttribute("disabled", "true");
  spriteBtn.addEventListener("click", () => {
    useSprites = !useSprites;
    spriteBtn.textContent = `Sprites: ${useSprites ? "on" : "off"}`;
    drawBoard();
  });
}
// Fog toggle: "on" = what the model saw (fogged); "off" = full ground truth. Enabled only when the
// current board carries an `unfogged` companion. Refreshed on each selection (see updateFogBtn).
const fogBtn = document.getElementById("fogBtn");
if (fogBtn) {
  fogBtn.addEventListener("click", () => {
    if (!boardHasFog(currentBoard())) return;
    showFog = !showFog;
    updateFogBtn();
    drawBoard();
  });
}
function updateFogBtn() {
  if (!fogBtn) return;
  const has = boardHasFog(currentBoard());
  if (has) fogBtn.removeAttribute("disabled");
  else fogBtn.setAttribute("disabled", "true");
  fogBtn.textContent = `Fog: ${showFog ? "on" : "off"}`;
  fogBtn.title = has
    ? (showFog ? "Showing what the model saw (fogged). Click for full ground truth."
               : "Showing full ground truth. Click to show what the model saw (fogged).")
    : "This board carries no separate ground truth (not a fogged export).";
}
document.addEventListener("keydown", (e) => {
  if (e.key === "ArrowRight" && !e.shiftKey) selectQuestion(selectedIndex + 1);
  else if (e.key === "ArrowLeft" && !e.shiftKey) selectQuestion(selectedIndex - 1);
  else if (e.key === "ArrowRight" && e.shiftKey) ($("stepNext") as HTMLButtonElement).click();
  else if (e.key === "ArrowLeft" && e.shiftKey) ($("stepPrev") as HTMLButtonElement).click();
});
window.addEventListener("resize", () => { viewInitForBoard = null; drawBoard(); });

($("fileInput") as HTMLInputElement).addEventListener("change", (e) => {
  const file = (e.target as HTMLInputElement).files?.[0]; if (!file) return;
  const reader = new FileReader();
  reader.onload = () => {
    try { loadData(JSON.parse(reader.result as string) as ExportD); }
    catch (err) { alert("Failed to parse JSON: " + err); }
  };
  reader.readAsText(file);
});

// Drag-and-drop a JSON export anywhere.
document.addEventListener("dragover", (e) => e.preventDefault());
document.addEventListener("drop", (e) => {
  e.preventDefault();
  const file = e.dataTransfer?.files?.[0]; if (!file) return;
  const reader = new FileReader();
  reader.onload = () => { try { loadData(JSON.parse(reader.result as string) as ExportD); } catch (err) { alert("Bad JSON: " + err); } };
  reader.readAsText(file);
});

// Center header shows the FULL question identifier (item_id) when a question is selected, with a copy
// button — the sidebar row clips long ids like `constraint-site:<player>:59,29,22,43,…`.
function updateCenterTitle(q: QuestionD) {
  const title = document.getElementById("centerTitle");
  if (title) title.textContent = q.item_id;
  const btn = document.getElementById("copyIdBtn");
  if (btn) btn.removeAttribute("hidden");
}

// A compact, UNIQUE identifier for a question, robust to identical-parameter duplicates: the source
// trace filename (one file per question) plus the trace dir make it unambiguous even if the
// (encoding, board, item) triple ever repeats.
function questionIdentifier(q: QuestionD): string {
  const traceDir = DATA?.meta?.trace_dir ?? "";
  const parts = [`enc=${q.encoding}`, `board=${q.board_ref}`, `item=${q.item_id}`];
  if (q.trace_file) parts.push(`trace=${traceDir ? traceDir + "/" : ""}${q.trace_file}`);
  return parts.join(" | ");
}

function fallbackCopy(text: string): boolean {
  try {
    const ta = document.createElement("textarea");
    ta.value = text; ta.style.position = "fixed"; ta.style.opacity = "0";
    document.body.appendChild(ta); ta.focus(); ta.select();
    const ok = document.execCommand("copy");
    document.body.removeChild(ta);
    return ok;
  } catch { return false; }
}

const copyIdBtn = document.getElementById("copyIdBtn");
if (copyIdBtn) {
  copyIdBtn.addEventListener("click", async () => {
    const q = currentQuestion(); if (!q) return;
    const text = questionIdentifier(q);
    let ok = false;
    // navigator.clipboard needs a secure context; on plain file:// it may reject — fall back to the
    // classic textarea+execCommand path so copy works fully offline.
    try { await navigator.clipboard.writeText(text); ok = true; } catch { ok = fallbackCopy(text); }
    const prev = copyIdBtn.textContent;
    copyIdBtn.textContent = ok ? "Copied!" : "Copy failed";
    setTimeout(() => { copyIdBtn.textContent = prev ?? "Copy id"; }, 1200);
  });
}

// Theme toggle (stamps data-theme; CSS handles both directions).
$("themeBtn").addEventListener("click", () => {
  const root = document.documentElement;
  const cur = root.getAttribute("data-theme");
  const prefersDark = window.matchMedia("(prefers-color-scheme: dark)").matches;
  const now = cur ? cur : (prefersDark ? "dark" : "light");
  root.setAttribute("data-theme", now === "dark" ? "light" : "dark");
  drawBoard();
});

// ---------------------------------------------------------------------------
// Tileset image loading — decode the inlined trident sheets, then redraw once ready.
// ---------------------------------------------------------------------------
function loadTileset() {
  if (!TILESET) return;
  const entries = Object.entries(TILESET.sheets);
  let pending = entries.length;
  if (!pending) return;
  for (const [key, dataUri] of entries) {
    const img = new Image();
    img.onload = () => { if (--pending === 0) { spritesReady = true; drawBoard(); } };
    img.onerror = () => { if (--pending === 0) { spritesReady = true; drawBoard(); } };
    img.src = dataUri;
    sheetImages[key] = img;
  }
}

// ---------------------------------------------------------------------------
// Tool playground — run ANY of the eval's model-facing tools against the CURRENT view board, through
// the REAL Rust dispatch compiled to wasm (civ_eval::run_tool). Nothing here re-implements a tool;
// parity with the eval is the whole point. The board is serialized to the export shape and handed to
// the wasm on each Run, so the Fog toggle (currentView) automatically re-targets the tools.
// ---------------------------------------------------------------------------
interface WasmExports {
  memory: WebAssembly.Memory;
  alloc(len: number): number;
  dealloc(ptr: number, len: number): void;
  run_tool(bp: number, bl: number, np: number, nl: number, ap: number, al: number): number;
}
let wasm: WasmExports | null = null;
let wasmStatus = "loading wasm…";

function initWasm() {
  const b64 = (window as unknown as { __CIVSPATIAL_WASM__?: string }).__CIVSPATIAL_WASM__;
  if (!b64) { wasmStatus = "tool wasm not bundled — run `npm run build:wasm`"; updateToolRunEnabled(); return; }
  try {
    const bin = atob(b64);
    const bytes = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
    WebAssembly.instantiate(bytes, {}).then(res => {
      wasm = res.instance.exports as unknown as WasmExports;
      wasmStatus = "";
      updateToolRunEnabled();
    }).catch(err => { wasmStatus = "wasm failed to load: " + err; updateToolRunEnabled(); });
  } catch (err) { wasmStatus = "wasm decode failed: " + err; updateToolRunEnabled(); }
}

// Marshal three strings across the raw C ABI and read back the length-prefixed result. Memory can
// grow during the call, so the result view is taken AFTER run_tool returns.
function wasmRunTool(boardJson: string, name: string, argsJson: string): string {
  if (!wasm) return wasmStatus || "wasm not ready";
  const w = wasm;
  const enc = new TextEncoder(), dec = new TextDecoder();
  const write = (s: string) => {
    const b = enc.encode(s);
    const ptr = w.alloc(b.length);
    new Uint8Array(w.memory.buffer).set(b, ptr);
    return { ptr, len: b.length };
  };
  const bj = write(boardJson), nm = write(name), ar = write(argsJson);
  const rptr = w.run_tool(bj.ptr, bj.len, nm.ptr, nm.len, ar.ptr, ar.len);
  const view = new DataView(w.memory.buffer);
  const len = view.getUint32(rptr, true);
  const out = dec.decode(new Uint8Array(w.memory.buffer).slice(rptr + 4, rptr + 4 + len));
  w.dealloc(rptr, 4 + len);
  w.dealloc(bj.ptr, bj.len); w.dealloc(nm.ptr, nm.len); w.dealloc(ar.ptr, ar.len);
  return out;
}

// Serialize the CURRENT view (fogged vs unfogged per the Fog toggle) to the per-board export JSON that
// Board::from_viewer_json expects. cities/units/tiles are already in the export shape.
function serializeViewBoard(board: BoardD): string {
  const vw = currentView(board);
  return JSON.stringify({
    source: board.source, width: board.width, height: board.height,
    tiles: vw.tiles, cities: vw.cities, units: vw.units,
    players: board.players ?? [], perspective: board.perspective,
  });
}

// --- static per-tool arg spec (the 29 tools run_tool dispatches, grouped) ------------------------
type ArgKind = "int" | "str" | "bool";
interface ArgSpec { key: string; kind: ArgKind; optional?: boolean; player?: boolean; }
interface ToolSpec { name: string; group: string; desc: string; args: ArgSpec[]; }
const I = (key: string, optional = false): ArgSpec => ({ key, kind: "int", optional });
const S = (key: string, optional = false, player = false): ArgSpec => ({ key, kind: "str", optional, player });
const B = (key: string, optional = false): ArgSpec => ({ key, kind: "bool", optional });
const box: ArgSpec[] = [I("x0"), I("y0"), I("x1"), I("y1")];

const TOOL_SPECS: ToolSpec[] = [
  // Perception / fetch verbs
  { name: "get_tile", group: "Perception", desc: "Exact facts of one tile (x, y).", args: [I("x"), I("y")] },
  { name: "scan", group: "Perception", desc: "Exact facts of every non-default tile in a box (max 12×12).", args: box },
  { name: "scan_grid", group: "Perception", desc: "Compact glyph grid + detail for a box, in one call.", args: box },
  { name: "scan_region", group: "Perception", desc: "Per-tile TERRAIN layer of the 10×10 area centered on (x, y): one line per known tile (terrain, resource, features, borders, [city]/[unit] flag). Occupants are in the roster; shifts to stay on-board.", args: [I("x"), I("y")] },
  { name: "region_summary", group: "Perception", desc: "EXACT occupants + resources + dominant terrain of the 10×10 area centered on (x, y); shifts to stay on-board at an edge.", args: [I("x"), I("y")] },
  { name: "list_cities", group: "Perception", desc: "Every visible city — name, owner, coords, size.", args: [] },
  { name: "list_units", group: "Perception", desc: "Every visible unit — id, type, owner, coords.", args: [] },
  // Spatial measurement
  { name: "distance", group: "Measure · spatial", desc: "Chebyshev (king-move) distance between two points.", args: box },
  { name: "travel_turns", group: "Measure · spatial", desc: "Land travel turns (1/turn, ocean impassable, 8-connected).", args: box },
  { name: "count", group: "Measure · spatial", desc: "Count tiles matching feature in a box; kind = terrain | resource.", args: [...box, S("kind"), S("feature")] },
  { name: "reach_turns", group: "Measure · spatial", desc: "Turns for unit #id to reach (tx, ty) at its own move rate (land).", args: [I("unit"), I("tx"), I("ty")] },
  // Combat / valuation
  { name: "att_eff", group: "Measure · combat", desc: "Effective attack strength of unit #id.", args: [I("unit")] },
  { name: "def_eff", group: "Measure · combat", desc: "Defense of unit #id — contextual by default; bare=true for context-free base.", args: [I("unit"), B("bare", true)] },
  { name: "win_prob", group: "Measure · combat", desc: "P(attacker #a beats defender #d).", args: [I("attacker"), I("defender")] },
  { name: "city_defense", group: "Measure · combat", desc: "Best garrison defense of the city at (x, y).", args: [I("x"), I("y")] },
  { name: "city_fall_prob", group: "Measure · combat", desc: "P(city at (x,y) falls this turn) from player's viewpoint.", args: [I("x"), I("y"), S("player", false, true)] },
  { name: "garrison_defense", group: "Measure · combat", desc: "Defense unit #id WOULD have garrisoning the city at (cx, cy).", args: [I("unit"), I("cx"), I("cy")] },
  { name: "threat", group: "Measure · combat", desc: "Graded incoming enemy-land threat at (x, y) for player.", args: [I("x"), I("y"), S("player", false, true)] },
  { name: "site_axes", group: "Measure · combat", desc: "Settle-site axes (food/production/resources/safety) at (x, y).", args: [I("x"), I("y"), S("player", false, true)] },
  { name: "tile_cover", group: "Measure · combat", desc: "Friendly cover at (x, y) for player.", args: [I("x"), I("y"), S("player", false, true)] },
  { name: "support", group: "Measure · combat", desc: "Count of player's supporting units near (x, y); optional exclude id.", args: [I("x"), I("y"), S("player", false, true), I("exclude", true)] },
  { name: "site_check", group: "Measure · combat", desc: "Site constraints at (x, y) for player: defensible + within_water + not_enemy (+ ok).", args: [I("x"), I("y"), S("player", false, true)] },
  // Enumeration / locating
  { name: "list_tiles", group: "Enumerate", desc: "Coordinates of tiles in a box matching terrain and/or resource (optional owner-radius exclusion).", args: [...box, S("terrain", true), S("resource", true), S("exclude_owner", true, true), I("exclude_radius", true)] },
  { name: "list_owned_cities", group: "Enumerate", desc: "Coordinates of every city a player owns.", args: [S("player", false, true)] },
  { name: "list_owned_units", group: "Enumerate", desc: "Every unit a player owns as '#id (x, y)'.", args: [S("player", false, true)] },
  { name: "travel_turns_from_owned", group: "Enumerate", desc: "Land turns from player's NEAREST city to (tx, ty).", args: [S("player", false, true), I("tx"), I("ty")] },
];

const UNIT_FIELDS = new Set(["unit", "attacker", "defender", "exclude"]);
function coordPair(key: string): string | null {
  if (key === "x" || key === "y") return "xy";
  if (key === "x0" || key === "y0") return "p0";
  if (key === "x1" || key === "y1") return "p1";
  if (key === "cx" || key === "cy") return "c";
  if (key === "tx" || key === "ty") return "t";
  return null;
}
function pairKeys(pair: string): [string, string] {
  return pair === "xy" ? ["x", "y"] : pair === "p0" ? ["x0", "y0"] : pair === "p1" ? ["x1", "y1"]
    : pair === "c" ? ["cx", "cy"] : ["tx", "ty"];
}

let activeArgKey: string | null = null; // the tool field last focused (pick-from-map target)
const toolLog: { call: string; out: string; err: boolean }[] = [];

function toolInput(key: string): HTMLInputElement | null {
  return document.getElementById(`tp_${key}`) as HTMLInputElement | null;
}
function currentToolSpec(): ToolSpec | null {
  const sel = document.getElementById("toolSelect") as HTMLSelectElement | null;
  if (!sel) return null;
  return TOOL_SPECS.find(t => t.name === sel.value) ?? null;
}

function setupToolsPanel() {
  const sel = document.getElementById("toolSelect") as HTMLSelectElement | null;
  if (!sel) return;
  // Grouped <select>, each option labeled "name — one-line description".
  const groups = new Map<string, ToolSpec[]>();
  for (const t of TOOL_SPECS) (groups.get(t.group) ?? groups.set(t.group, []).get(t.group)!).push(t);
  sel.innerHTML = "";
  for (const [group, specs] of groups) {
    const og = document.createElement("optgroup"); og.label = group;
    for (const t of specs) {
      const o = document.createElement("option");
      o.value = t.name; o.textContent = `${t.name} — ${t.desc}`;
      og.appendChild(o);
    }
    sel.appendChild(og);
  }
  sel.addEventListener("change", renderToolParams);
  (document.getElementById("toolRun") as HTMLButtonElement).addEventListener("click", runCurrentTool);
  renderToolParams();
  updateToolRunEnabled();
}

function renderToolParams() {
  const spec = currentToolSpec();
  const params = document.getElementById("toolParams")!;
  const desc = document.getElementById("toolDesc")!;
  const units = document.getElementById("toolUnits")!;
  params.innerHTML = ""; units.innerHTML = ""; activeArgKey = null;
  if (!spec) { desc.textContent = ""; return; }
  desc.textContent = spec.desc;
  const persp = currentBoard()?.perspective ?? "";
  if (!spec.args.length) {
    const none = document.createElement("div"); none.className = "tooldesc"; none.textContent = "(no parameters)";
    params.appendChild(none);
  }
  for (const a of spec.args) {
    const wrap = document.createElement("div"); wrap.className = "toolparam";
    const lab = document.createElement("label");
    lab.innerHTML = escapeHtml(a.key) + (a.optional ? ` <span class="opt">(optional)</span>` : "");
    const inp = document.createElement("input");
    inp.id = `tp_${a.key}`;
    inp.autocomplete = "off";
    inp.placeholder = a.kind === "int" ? (coordPair(a.key) || UNIT_FIELDS.has(a.key) ? "click map / type" : "integer") : a.kind === "bool" ? "true / false" : (a.player ? "player" : a.key);
    if (a.kind === "int" && (coordPair(a.key) || UNIT_FIELDS.has(a.key))) inp.classList.add("pickable");
    if (a.player && persp) inp.value = persp; // player fields default to the board's perspective
    inp.addEventListener("focus", () => { activeArgKey = a.key; updatePickHint(); });
    wrap.appendChild(lab); wrap.appendChild(inp); params.appendChild(wrap);
  }
  updatePickHint();
}

function updatePickHint() {
  const hint = document.getElementById("toolPickHint")!;
  if (!wasm && wasmStatus) { hint.textContent = wasmStatus; return; }
  const fog = currentBoard()?.unfogged ? (showFog ? " · runs on the FOGGED view" : " · runs on GROUND TRUTH") : "";
  if (activeArgKey && (coordPair(activeArgKey) || UNIT_FIELDS.has(activeArgKey))) {
    hint.textContent = `click a tile to fill ${activeArgKey}${fog}`;
  } else {
    hint.textContent = `focus a coord/unit field, then click the map to fill it${fog}`;
  }
}

// Fill the focused tool field from a clicked tile: coord pairs set both x/y; unit fields take a unit
// id on the tile (with a chooser when several are stacked); terrain/resource/player fields read the
// tile's own facts. No-op when no field is focused.
function toolsPickTile(x: number, y: number, board: BoardD) {
  const units = document.getElementById("toolUnits");
  if (units) units.innerHTML = "";
  if (!activeArgKey) return;
  const key = activeArgKey;
  const pair = coordPair(key);
  if (pair) {
    const [kx, ky] = pairKeys(pair);
    const ix = toolInput(kx), iy = toolInput(ky);
    if (ix) ix.value = String(x);
    if (iy) iy.value = String(y);
    return;
  }
  const vw = currentView(board);
  if (UNIT_FIELDS.has(key)) {
    const here = vw.units.filter(u => u.x === x && u.y === y);
    const inp = toolInput(key);
    if (!here.length) { const h = document.getElementById("toolPickHint")!; h.textContent = `no units on (${x}, ${y})`; return; }
    if (inp) inp.value = String(here[0].id);
    if (here.length > 1 && units) { // stacked: offer a chooser
      for (const u of here) {
        const b = document.createElement("button"); b.className = "btn";
        b.textContent = `#${u.id} ${u.kind}`;
        b.onclick = () => { const i = toolInput(key); if (i) i.value = String(u.id); };
        units.appendChild(b);
      }
    }
    return;
  }
  // string facts
  const t = vw.tiles[y * board.width + x];
  if (key === "terrain" && t) { const i = toolInput(key); if (i) i.value = t.terrain; return; }
  if (key === "resource" && t) {
    const infra = new Set(["River", "Road", "Railroad", "Irrigation", "Mine", "Farmland", "Fortress", "Airbase", "Pollution", "Fallout", "Hut"]);
    const res = t.extras.find(e => !infra.has(e));
    const i = toolInput(key); if (i && res) i.value = res; return;
  }
  if ((key === "player" || key === "exclude_owner") && t && t.owner) { const i = toolInput(key); if (i) i.value = t.owner; return; }
}

// Populate player-type fields with the current board's perspective ("you"), but only when the field
// is empty so we never clobber a value the user typed. Called when the selected board may have changed.
function refreshToolPlayerDefaults() {
  const spec = currentToolSpec(); if (!spec) return;
  const persp = currentBoard()?.perspective ?? "";
  if (!persp) return;
  for (const a of spec.args) {
    if (!a.player) continue;
    const inp = toolInput(a.key);
    if (inp && inp.value.trim() === "") inp.value = persp;
  }
}

function buildArgsJson(spec: ToolSpec): string {
  const parts: string[] = [];
  for (const a of spec.args) {
    const v = (toolInput(a.key)?.value ?? "").trim();
    if (v === "") continue; // omit empties — Rust returns a clear "requires …" error for missing ones
    if (a.kind === "int") parts.push(`${JSON.stringify(a.key)}:${v}`);
    else if (a.kind === "bool") parts.push(`${JSON.stringify(a.key)}:${/^(true|1|yes)$/i.test(v) ? "true" : "false"}`);
    else parts.push(`${JSON.stringify(a.key)}:${JSON.stringify(v)}`);
  }
  return `{${parts.join(",")}}`;
}

function updateToolRunEnabled() {
  const btn = document.getElementById("toolRun") as HTMLButtonElement | null;
  if (btn) btn.disabled = !wasm;
  const hint = document.getElementById("toolPickHint");
  if (hint && !wasm) hint.textContent = wasmStatus;
}

function runCurrentTool() {
  const spec = currentToolSpec();
  const board = currentBoard();
  const out = document.getElementById("toolOut")!;
  if (!spec) return;
  if (!board) { out.textContent = "Load a board first."; out.classList.add("err"); return; }
  if (!wasm) { out.textContent = wasmStatus || "wasm not ready"; out.classList.add("err"); return; }
  const args = buildArgsJson(spec);
  let result: string;
  try { result = wasmRunTool(serializeViewBoard(board), spec.name, args); }
  catch (e) { result = "error: " + e; }
  const isErr = result.startsWith("error:");
  out.textContent = result;
  out.classList.toggle("err", isErr);
  // Scrollback (most-recent first, capped).
  toolLog.unshift({ call: `${spec.name}(${args})`, out: result, err: isErr });
  if (toolLog.length > 20) toolLog.pop();
  renderToolLog();
}

function renderToolLog() {
  const host = document.getElementById("toolLog"); if (!host) return;
  host.innerHTML = "";
  for (const e of toolLog) {
    const item = document.createElement("div"); item.className = "toollog-item";
    const call = document.createElement("div"); call.className = "toollog-call"; call.textContent = e.call;
    const res = document.createElement("div"); res.className = "toollog-out" + (e.err ? " err" : ""); res.textContent = e.out;
    item.appendChild(call); item.appendChild(res); host.appendChild(item);
  }
}

// ---------------------------------------------------------------------------
// Tabbed windows (items 1 & 5): a strip of tab buttons whose `data-tab` selects a matching pane.
// ---------------------------------------------------------------------------
function setupWindowTabs(rootId: string) {
  const root = document.getElementById(rootId); if (!root) return;
  const tabs = Array.from(root.querySelectorAll<HTMLButtonElement>(".wintab"));
  const panes = Array.from(root.querySelectorAll<HTMLElement>(".wintab-pane"));
  for (const tab of tabs) {
    tab.addEventListener("click", () => {
      const name = tab.dataset.tab;
      for (const t of tabs) t.classList.toggle("active", t === tab);
      for (const p of panes) p.hidden = p.dataset.pane !== name;
      // The board canvas needs a (re)fit whenever its pane becomes visible again — while hidden its
      // wrapper has zero width, so any fit computed then would be wrong.
      if (name === "board") { viewInitForBoard = null; drawBoard(); }
    });
  }
}

// ---------------------------------------------------------------------------
// Stats / Compare view (item 7): combine filters to aggregate accuracy, latency and token usage over
// the matching subset, with an optional side-by-side compare mode (a left and a right filter combo).
// Reuses the replay filter logic (filterQuestions) and the same category/encoding/result dimensions.
// ---------------------------------------------------------------------------
type StatsSide = "L" | "R";
interface StatsSel { cat: string; enc: string; status: string; model: string; }
const statsSel: Record<StatsSide, StatsSel> = { L: { cat: "", enc: "", status: "", model: "" }, R: { cat: "", enc: "", status: "", model: "" } };
let statsCompare = false;

// The category/encoding/model option sets present in the loaded data (mirrors populateFilters).
type OptSets = { cats: Set<string>; encs: Set<string>; models: Set<string> };
function optionSets(): OptSets {
  const cats = new Set<string>(), encs = new Set<string>(), models = new Set<string>();
  for (const q of DATA?.questions ?? []) { cats.add(q.category); encs.add(q.encoding); if (q.model) models.add(q.model); }
  return { cats, encs, models };
}

function renderStats() {
  const grid = document.getElementById("statsGrid"); if (!grid) return;
  const btn = document.getElementById("statsCompareBtn");
  if (btn) btn.textContent = `Compare: ${statsCompare ? "on" : "off"}`;
  grid.className = "statsgrid" + (statsCompare ? " compare" : "");
  grid.innerHTML = "";
  if (!DATA) { grid.innerHTML = `<div class="empty">Load an export JSON to see stats.</div>`; return; }
  const opts = optionSets();
  grid.appendChild(makeStatsPanel("L", opts));
  if (statsCompare) grid.appendChild(makeStatsPanel("R", opts));
}

// One filter combo + its aggregate results. Selections persist in statsSel across compare toggles.
function makeStatsPanel(side: StatsSide, opts: OptSets): HTMLElement {
  const panel = document.createElement("div"); panel.className = "panel statspanel";
  const filt = document.createElement("div"); filt.className = "statsfilters";
  // The run/model select is only shown when the bundle actually mixes runs.
  const mdl = opts.models.size > 1 ? statsSelect("model", side, opts) : null;
  const cat = statsSelect("cat", side, opts);
  const enc = statsSelect("enc", side, opts);
  const st = statsSelect("status", side, opts);
  if (mdl) filt.appendChild(mdl);
  filt.appendChild(cat); filt.appendChild(enc); filt.appendChild(st);
  const results = document.createElement("div"); results.className = "statsresults";
  panel.appendChild(filt); panel.appendChild(results);
  const recompute = () => {
    statsSel[side] = { cat: cat.value, enc: enc.value, status: st.value, model: mdl ? mdl.value : "" };
    renderStatsResults(results, statsSel[side]);
  };
  cat.onchange = enc.onchange = st.onchange = recompute;
  if (mdl) mdl.onchange = recompute;
  recompute();
  return panel;
}

function statsSelect(kind: "cat" | "enc" | "status" | "model", side: StatsSide,
                     opts: OptSets): HTMLSelectElement {
  const sel = document.createElement("select");
  const add = (val: string, label: string) => { const o = document.createElement("option"); o.value = val; o.textContent = label; sel.appendChild(o); };
  if (kind === "cat") { add("", "All categories"); for (const v of [...opts.cats].sort()) add(v, v); sel.value = statsSel[side].cat; }
  else if (kind === "enc") { add("", "All encodings"); for (const v of [...opts.encs].sort()) add(v, v); sel.value = statsSel[side].enc; }
  else if (kind === "model") { add("", "All runs"); for (const v of [...opts.models].sort()) add(v, v); sel.value = statsSel[side].model; }
  else {
    add("", "All results"); add("correct", "Correct only"); add("wrong", "Wrong only"); add("invalid", "Invalid only");
    sel.value = statsSel[side].status;
  }
  return sel;
}

function renderStatsResults(host: HTMLElement, sel: StatsSel) {
  host.innerHTML = "";
  const qs = filterQuestions(sel.cat, sel.enc, sel.status, sel.model);
  const count = document.createElement("div"); count.className = "statscount";
  count.innerHTML = `<b>${qs.length.toLocaleString()}</b> question${qs.length === 1 ? "" : "s"} match`;
  host.appendChild(count);
  if (!qs.length) { const e = document.createElement("div"); e.className = "statempty"; e.textContent = "No questions match this filter."; host.appendChild(e); return; }
  // Gather the raw series in one pass: accuracy count, latency (ms), total tokens (prompt+completion),
  // turn count and time-per-turn (latency_ms / n_turns). Turns/time-per-turn cover the tool-loop
  // encodings only: static encodings have no turns, so we include a question only when n_turns is
  // present and > 0 — keeping static questions out of both series (no skew, no divide-by-zero).
  let correct = 0; const lat: number[] = [], tok: number[] = [], turns: number[] = [], tpt: number[] = [], tpq: number[] = [];
  for (const q of qs) {
    if (statusBucket(q.status) === "correct") correct++;
    if (q.latency_ms != null) lat.push(q.latency_ms);
    if (q.prompt_tokens != null || q.completion_tokens != null) tok.push((q.prompt_tokens ?? 0) + (q.completion_tokens ?? 0));
    if (q.n_turns != null && q.n_turns > 0) {
      turns.push(q.n_turns);
      if (q.latency_ms != null) tpt.push(q.latency_ms / q.n_turns);
      // Tool calls per question — same multi-turn guard as Turns so static/one-shot encodings can't skew.
      if (q.n_tool_calls != null) tpq.push(q.n_tool_calls);
    }
  }
  host.appendChild(accuracyBlock(correct, qs.length));
  host.appendChild(distBlock("Latency", lat, fmtMs));
  host.appendChild(distBlock("Token usage (prompt + completion)", tok, (n) => Math.round(n).toLocaleString()));
  host.appendChild(distBlock("Turns", turns, (n) => Math.round(n).toLocaleString()));
  host.appendChild(distBlock("Time per turn", tpt, fmtMs));
  host.appendChild(distBlock("Tool calls per question", tpq, (n) => Math.round(n).toLocaleString()));
  // Analytics moved out of the Board tab and rendered at the BOTTOM of the stats section — per-side, so
  // they honor this side's filter combo in Compare mode exactly like the aggregates above.
  host.appendChild(crossTurnRepeatBlock(qs));
  host.appendChild(toolCallHistBlock(qs));
}

// ---------------------------------------------------------------------------
// Cross-turn repeat-call analytics (item 6). For each question we count, per tool, the number of
// DISTINCT turns that tool appears in (multiple calls of the SAME tool within ONE turn count once). A
// tool "repeats across turns" for a question when it appears in ≥2 different turns — an iterative /
// over-fetch / converging-behavior signal. Reported over the filtered subset as (a) the headline
// incidence "% of questions where SOME tool is called in ≥2 different turns", and (b) a per-tool
// breakdown of the % of questions each tool crosses that ≥2-turn bar (bar width = that %), with the
// average distinct-turn count when the tool appears (≥1 turn) shown in the count column + tooltip.
// Denominator: only questions with a multi-turn trajectory (n_turns > 0) — mirrors the Turns /
// Time-per-turn guard so static encodings can't skew the rate or divide-by-zero.
// ---------------------------------------------------------------------------
function crossTurnRepeatBlock(qs: QuestionD[]): HTMLElement {
  // analytics-start forces this (the first of the two analytics blocks) onto a fresh grid row so the
  // cross-turn + tool-call-totals pair always sits together, and the odd 5th aggregate block above
  // (Time per turn) is left alone on its own row rather than pairing with an analytics block.
  const b = document.createElement("div"); b.className = "statblock analytics-start";
  const h = document.createElement("div"); h.className = "statssub"; h.textContent = "Cross-turn repeat tool use";
  b.appendChild(h);
  const eligible = qs.filter(q => q.n_turns != null && q.n_turns > 0 && q.trajectory && q.trajectory.length > 0);
  if (!eligible.length) {
    const e = document.createElement("div"); e.className = "statempty";
    e.textContent = "No multi-turn trajectories in this subset.";
    b.appendChild(e); return b;
  }
  let anyRepeat = 0;                              // #questions where SOME tool spans ≥2 distinct turns
  const repeatQs = new Map<string, number>();    // tool -> #questions where it spans ≥2 distinct turns
  const appearQs = new Map<string, number>();    // tool -> #questions where it appears in ≥1 turn
  const distinctSum = new Map<string, number>(); // tool -> Σ distinct-turn counts over appearing questions
  for (const q of eligible) {
    const perTool = new Map<string, Set<number>>(); // tool -> set of turn indices it was called in
    q.trajectory!.forEach((turn, ti) => {
      for (const c of turn.tool_calls) (perTool.get(c.name) ?? perTool.set(c.name, new Set()).get(c.name)!).add(ti);
    });
    let repeatedHere = false;
    for (const [name, turnSet] of perTool) {
      const d = turnSet.size;
      appearQs.set(name, (appearQs.get(name) ?? 0) + 1);
      distinctSum.set(name, (distinctSum.get(name) ?? 0) + d);
      if (d >= 2) { repeatQs.set(name, (repeatQs.get(name) ?? 0) + 1); repeatedHere = true; }
    }
    if (repeatedHere) anyRepeat++;
  }
  const big = document.createElement("div"); big.className = "acc-big";
  big.textContent = `${(100 * anyRepeat / eligible.length).toFixed(1)}%`;
  b.appendChild(big);
  const sub = document.createElement("div"); sub.className = "statquant";
  sub.textContent = `${anyRepeat.toLocaleString()} of ${eligible.length.toLocaleString()} multi-turn ` +
    `question${eligible.length === 1 ? "" : "s"} call some tool in ≥2 different turns`;
  b.appendChild(sub);
  // Per-tool breakdown, sorted by repeat-incidence desc then name. Only tools that appear at all are
  // listed (a full-roster wall of 0% would be pure noise here, unlike the total-calls histogram which
  // deliberately seeds every tool). Bar width = the repeat-% directly (0–100), so it reads as the rate.
  const tools = [...appearQs.keys()].sort((a, c) =>
    (repeatQs.get(c) ?? 0) - (repeatQs.get(a) ?? 0) || a.localeCompare(c));
  if (tools.length) {
    const list = document.createElement("div"); list.className = "analytics-list";
    for (const name of tools) {
      const rq = repeatQs.get(name) ?? 0;
      const pct = 100 * rq / eligible.length;
      const avgDistinct = (distinctSum.get(name) ?? 0) / (appearQs.get(name) ?? 1);
      const row = document.createElement("div"); row.className = "abar";
      const lbl = document.createElement("span"); lbl.className = "an"; lbl.textContent = name; lbl.title = name;
      const track = document.createElement("span"); track.className = "atrack";
      const fill = document.createElement("span"); fill.className = "afill"; fill.style.width = `${pct}%`;
      track.appendChild(fill);
      const cnt = document.createElement("span"); cnt.className = "ac"; cnt.textContent = `${pct.toFixed(0)}%`;
      row.title = `${name}: repeats across ≥2 turns in ${rq.toLocaleString()} of ${eligible.length.toLocaleString()} ` +
        `question${eligible.length === 1 ? "" : "s"} (${pct.toFixed(1)}%); avg ${avgDistinct.toFixed(1)} distinct turns when present`;
      row.appendChild(lbl); row.appendChild(track); row.appendChild(cnt);
      list.appendChild(row);
    }
    b.appendChild(list);
  }
  return b;
}

// ---------------------------------------------------------------------------
// Tool-call totals histogram (item 3, relocated). A per-tool bar list SUMMED over this side's filtered
// subset, sourced from each question's `tool_call_counts` (viewer_export.rs tallies every turn's
// tool_calls). Seeds the full TOOL_SPECS roster at 0 so EVERY known tool renders — uncalled ones show a
// 0 bar (kept from the earlier zero-call fix). Formerly a Board tab; now the bottom of the stats section.
// ---------------------------------------------------------------------------
function toolCallHistBlock(qs: QuestionD[]): HTMLElement {
  const b = document.createElement("div"); b.className = "statblock";
  const h = document.createElement("div"); h.className = "statssub"; h.textContent = "Tool-call totals";
  b.appendChild(h);
  const counts = new Map<string, number>();
  for (const t of TOOL_SPECS) counts.set(t.name, 0);
  let grand = 0;
  for (const q of qs) {
    const tc = q.tool_call_counts; if (!tc) continue;
    for (const name of Object.keys(tc)) { const n = tc[name]; counts.set(name, (counts.get(name) ?? 0) + n); grand += n; }
  }
  const sub = document.createElement("div"); sub.className = "statquant";
  sub.textContent = `${qs.length.toLocaleString()} Q · ${grand.toLocaleString()} calls`;
  b.appendChild(sub);
  // Empty state ONLY when nothing was called at all (e.g. a static-encoding-only filter) — otherwise a
  // wall of all-zero bars would show.
  if (!grand) {
    const e = document.createElement("div"); e.className = "statempty";
    e.textContent = "No tool calls in this subset."; b.appendChild(e); return b;
  }
  const rows = [...counts.entries()].sort((a, c) => c[1] - a[1] || a[0].localeCompare(c[0]));
  const max = rows[0][1];
  const list = document.createElement("div"); list.className = "analytics-list";
  for (const [name, n] of rows) {
    const row = document.createElement("div"); row.className = "abar";
    const lbl = document.createElement("span"); lbl.className = "an"; lbl.textContent = name; lbl.title = name;
    const track = document.createElement("span"); track.className = "atrack";
    const fill = document.createElement("span"); fill.className = "afill"; fill.style.width = `${(n / max) * 100}%`;
    track.appendChild(fill);
    const cnt = document.createElement("span"); cnt.className = "ac"; cnt.textContent = n.toLocaleString();
    row.appendChild(lbl); row.appendChild(track); row.appendChild(cnt);
    list.appendChild(row);
  }
  b.appendChild(list);
  return b;
}

function accuracyBlock(correct: number, total: number): HTMLElement {
  const b = document.createElement("div"); b.className = "statblock";
  const h = document.createElement("div"); h.className = "statssub"; h.textContent = "Accuracy";
  const big = document.createElement("div"); big.className = "acc-big";
  big.textContent = `${(total ? (100 * correct / total) : 0).toFixed(1)}%`;
  const sub = document.createElement("div"); sub.className = "statquant";
  sub.textContent = `${correct.toLocaleString()} correct / ${total.toLocaleString()} total`;
  b.appendChild(h); b.appendChild(big); b.appendChild(sub);
  return b;
}

// A distribution block: average / median / max stat tiles, a min·p25·p75 quantile line, and a small
// histogram (the chosen distribution descriptor). Degrades to a note when the export omits the metric.
function distBlock(label: string, vals: number[], fmt: (n: number) => string): HTMLElement {
  const b = document.createElement("div"); b.className = "statblock";
  const h = document.createElement("div"); h.className = "statssub"; h.textContent = label;
  b.appendChild(h);
  if (!vals.length) { const e = document.createElement("div"); e.className = "statempty"; e.textContent = "Not recorded in this export."; b.appendChild(e); return b; }
  const s = [...vals].sort((a, c) => a - c);
  const avg = vals.reduce((a, c) => a + c, 0) / vals.length;
  const three = document.createElement("div"); three.className = "three";
  three.appendChild(statTile("Average", fmt(avg)));
  three.appendChild(statTile("Median", fmt(quantile(s, 0.5))));
  three.appendChild(statTile("Max", fmt(s[s.length - 1])));
  b.appendChild(three);
  const q = document.createElement("div"); q.className = "statquant";
  q.textContent = `min ${fmt(s[0])} · p25 ${fmt(quantile(s, 0.25))} · p75 ${fmt(quantile(s, 0.75))} · n=${vals.length}`;
  b.appendChild(q);
  b.appendChild(histogram(s, fmt));
  return b;
}

function statTile(label: string, value: string): HTMLElement {
  const c = document.createElement("div"); c.className = "metric";
  const l = document.createElement("div"); l.className = "ml"; l.textContent = label;
  const v = document.createElement("div"); v.className = "mv"; v.textContent = value;
  c.appendChild(l); c.appendChild(v);
  return c;
}

// Linear-interpolated quantile over an ascending-sorted array.
function quantile(sorted: number[], p: number): number {
  if (!sorted.length) return 0;
  const idx = (sorted.length - 1) * p, lo = Math.floor(idx), hi = Math.ceil(idx);
  return lo === hi ? sorted[lo] : sorted[lo] + (sorted[hi] - sorted[lo]) * (idx - lo);
}

// A compact fixed-bin histogram rendered as DOM bars (theme-aware, no canvas). Each bar tooltips its
// value range and count.
function histogram(sorted: number[], fmt: (n: number) => string): HTMLElement {
  const wrap = document.createElement("div"); wrap.className = "hist";
  const BINS = 12, n = sorted.length, min = sorted[0], max = sorted[n - 1], span = max - min;
  const counts = new Array<number>(BINS).fill(0);
  for (const v of sorted) {
    let bi = span > 0 ? Math.floor((v - min) / span * BINS) : 0;
    if (bi >= BINS) bi = BINS - 1; if (bi < 0) bi = 0;
    counts[bi]++;
  }
  const cmax = Math.max(...counts, 1);
  for (let i = 0; i < BINS; i++) {
    const bar = document.createElement("div"); bar.className = "bin";
    bar.style.height = `${Math.max(1, (counts[i] / cmax) * 100)}%`;
    const lo = min + span * i / BINS, hi = min + span * (i + 1) / BINS;
    bar.title = `${fmt(lo)} – ${fmt(hi)}: ${counts[i]}`;
    wrap.appendChild(bar);
  }
  return wrap;
}

function fmtMs(ms: number): string { return ms >= 1000 ? (ms / 1000).toFixed(2) + " s" : Math.round(ms) + " ms"; }

const statsCompareBtn = document.getElementById("statsCompareBtn");
if (statsCompareBtn) statsCompareBtn.addEventListener("click", () => { statsCompare = !statsCompare; renderStats(); });

// ---------------------------------------------------------------------------
// Boot: ?data=URL (hosted), else bundled sample, else prompt for a file.
// ---------------------------------------------------------------------------
loadTileset();
initWasm();
setupToolsPanel();
setupWindowTabs("right"); // center no longer tabbed (analytics moved to the Aggregated Stats section)
renderStats(); // Stats / Compare renders permanently below the replay layout (populated once data loads).
(function boot() {
  const params = new URLSearchParams(location.search);
  const url = params.get("data");
  if (url) {
    fetch(url).then(r => r.json()).then(d => loadData(d as ExportD))
      .catch(err => { console.error(err); bootSampleOrEmpty(); });
    return;
  }
  bootSampleOrEmpty();
})();
function bootSampleOrEmpty() {
  const sample = (window as unknown as { __CIVSPATIAL_SAMPLE__?: ExportD }).__CIVSPATIAL_SAMPLE__;
  if (sample) loadData(sample);
  else $("qlist").innerHTML = `<div class="empty">Load an export JSON (button top-right, or drag a file in).</div>`;
}
