#!/usr/bin/env python3
"""Generate Freeciv server (`.serv`) scripts for the CivSpatial multi-board corpus.

WHY THIS EXISTS
---------------
The robustness experiment needs >=3 early / >=3 mid / >=3 late game boards (9+),
varied in size / density / contest, ALL on the `classic` ruleset. Rather than
scavenge community saves (unknown/mixed rulesets -> silently mismatch our
hard-coded `classic` combat constants), we GENERATE them by headless Freeciv
AI-vs-AI self-play. `classic` is then guaranteed by construction, and because the
map/game are seeded the whole corpus is reproducible from these tiny scripts --
so we commit the scripts, not the (gitignored) multi-MB `.sav` blobs.

WHAT IT EMITS
-------------
One `.serv` startup script per (size x aifill x seed) cell of the sweep, plus a
`sweep.json` sidecar recording the intended parameters keyed by `savename`
(the manifest step joins actual autosaves back to this by savename prefix, so we
never depend on Freeciv's exact autosave-filename format across versions).

Each script drives one autogame:
  * `rulesetdir classic`                      -> the guarantee
  * `set mapsize XYSIZE` + `set xsize/ysize`  -> deterministic dimensions
  * `set mapseed` / `set gameseed`            -> reproducible map + play
  * `set aifill N`                            -> N AI players (contest/density knob)
  * `set saveturns 20`                        -> a snapshot every 20 turns (the
                                                 early/mid/late ladder)
  * `set endturn ~220`                        -> a long-enough game for late boards
  * `set victories ""`                        -> disable spacerace/domination early-exit
                                                 (reduces premature game-over; last-man-
                                                 standing can still end it -- see README)
  * `set timeout <positive>`                  -> positive per task; with zero humans
                                                 connected the server still auto-advances
  * `set minplayers 0`                        -> let the all-AI game start with 0 humans
  * `set compresstype "PLAIN"`                -> plaintext `.sav` our parser reads directly
  * `set savename "corpus_..."`               -> encodes the cell into the filename
  * `start`                                   -> begin the all-AI game

SERVER-COMMAND CAVEAT
---------------------
Command/`set` names below are for Freeciv 3.2.x (our existing saves are
revision 3.2.90.2-dev). If a name differs on the installed build, verify against
the running server: `help set`, `show`, or `freeciv-server --help`. The README
lists the few names most likely to drift.

USAGE
-----
  python scripts/gen-corpus-scripts.py                 # default sweep
  python scripts/gen-corpus-scripts.py --sizes small,large --aifill 3,9 --seeds 42
  python scripts/gen-corpus-scripts.py --endturn 160 --saveturns 20 --out-dir data/corpus/scripts
"""
from __future__ import annotations

import argparse
import json
import os
from dataclasses import dataclass, asdict
from pathlib import Path

# Named size presets -> (xsize, ysize). Chosen to bracket our existing boards
# (T50 = 78x52 = 4056 tiles; T677 = 84x56 = 4704) with a smaller and a larger point.
SIZE_PRESETS: dict[str, tuple[int, int]] = {
    "small": (64, 40),   # 2560 tiles
    "medium": (80, 50),  # 4000 tiles (~ our current boards)
    "large": (96, 60),   # 5760 tiles
}


@dataclass(frozen=True)
class Cell:
    size_name: str
    xsize: int
    ysize: int
    aifill: int
    mapseed: int
    gameseed: int

    @property
    def savename(self) -> str:
        # Compact, filename-safe, and self-describing so a human (and the manifest
        # fallback) can read the cell straight off the autosave name.
        return f"corpus_{self.size_name}_a{self.aifill}_s{self.mapseed}"


def build_script(cell: Cell, endturn: int, saveturns: int, timeout: int) -> str:
    """Render one `.serv` startup script for a single autogame cell."""
    return f"""\
# CivSpatial corpus autogame -- generated by scripts/gen-corpus-scripts.py
# cell: size={cell.size_name} ({cell.xsize}x{cell.ysize}) aifill={cell.aifill} \
mapseed={cell.mapseed} gameseed={cell.gameseed}
# Reproducible: same seeds + same Freeciv version => same corpus.

# --- ruleset: the whole point of self-play (classic guaranteed by construction) ---
rulesetdir classic

# --- deterministic map dimensions ---
set mapsize XYSIZE
set xsize {cell.xsize}
set ysize {cell.ysize}

# --- reproducibility: seed BOTH the map and the game (AI decisions) ---
set mapseed {cell.mapseed}
set gameseed {cell.gameseed}

# --- contest / density knob: number of AI players ---
set aifill {cell.aifill}

# --- all-AI autogame: allow start with zero HUMAN players (default minplayers=1
#     refuses to start headless -> "Not enough human players ... game will not start") ---
set minplayers 0

# --- the early/mid/late snapshot ladder ---
set saveturns {saveturns}
set endturn {endturn}
set autosaves "TURN|GAMEOVER"

# --- keep the game running to endturn where possible (disable victory early-exit) ---
set victories ""

# --- positive per-turn timeout; with no human clients the server still auto-advances ---
set timeout {timeout}

# --- plaintext saves so our parser reads them directly (no decompression needed).
#     NOTE: `set compress 0` is INVALID on 3.2.5 (range 1..9); compresstype PLAIN alone
#     already means "No compression", verified live. ---
set compresstype "PLAIN"

# --- savename encodes the sweep cell; autosaves become <savename>-T<turn>-...sav ---
set savename "{cell.savename}"

# --- begin the all-AI game; with `freeciv-server -e` the server exits at endturn ---
start
"""


def make_sweep(sizes: list[str], aifills: list[int], seeds: list[int]) -> list[Cell]:
    cells: list[Cell] = []
    for size_name in sizes:
        if size_name not in SIZE_PRESETS:
            raise SystemExit(
                f"unknown size {size_name!r}; have: {', '.join(SIZE_PRESETS)}"
            )
        xs, ys = SIZE_PRESETS[size_name]
        for aifill in aifills:
            for seed in seeds:
                # Use the same seed for map and game so one integer names the cell;
                # they are separate settings so you *could* decorrelate them if wanted.
                cells.append(
                    Cell(size_name, xs, ys, aifill, mapseed=seed, gameseed=seed)
                )
    return cells


def parse_int_list(s: str) -> list[int]:
    return [int(x) for x in s.split(",") if x.strip()]


def parse_str_list(s: str) -> list[str]:
    return [x.strip() for x in s.split(",") if x.strip()]


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--sizes", default="small,medium,large",
                    help=f"comma list of size presets ({', '.join(SIZE_PRESETS)}); default all three")
    ap.add_argument("--aifill", default="3,6,9",
                    help="comma list of aifill values (players); default 3,6,9")
    ap.add_argument("--seeds", default="42,1337",
                    help="comma list of map/game seeds; default 42,1337")
    ap.add_argument("--endturn", type=int, default=220,
                    help="last turn before the server exits (needs a late-game tail); default 220")
    ap.add_argument("--saveturns", type=int, default=20,
                    help="autosave every N turns (the snapshot ladder); default 20")
    ap.add_argument("--timeout", type=int, default=3,
                    help="positive per-turn timeout seconds; default 3")
    ap.add_argument("--out-dir", default="data/corpus/scripts",
                    help="where to write the .serv scripts + sweep.json")
    args = ap.parse_args()

    sizes = parse_str_list(args.sizes)
    aifills = parse_int_list(args.aifill)
    seeds = parse_int_list(args.seeds)
    if args.endturn <= 0 or args.saveturns <= 0 or args.timeout <= 0:
        raise SystemExit("endturn, saveturns and timeout must all be positive")

    cells = make_sweep(sizes, aifills, seeds)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    sweep_index = {
        "meta": {
            "endturn": args.endturn,
            "saveturns": args.saveturns,
            "timeout": args.timeout,
            "ruleset": "classic",
            "n_games": len(cells),
            "band_thresholds": {"early_max": 60, "mid_max": 140},
        },
        "cells": {},
    }

    for cell in cells:
        script_path = out_dir / f"{cell.savename}.serv"
        script_path.write_text(build_script(cell, args.endturn, args.saveturns, args.timeout),
                               encoding="utf-8")
        sweep_index["cells"][cell.savename] = {
            **asdict(cell),
            "script": str(script_path).replace(os.sep, "/"),
            "expected_snapshots": list(range(args.saveturns, args.endturn + 1, args.saveturns)),
        }

    sweep_path = out_dir / "sweep.json"
    sweep_path.write_text(json.dumps(sweep_index, indent=2), encoding="utf-8")

    print(f"wrote {len(cells)} .serv scripts + sweep.json to {out_dir}/")
    print(f"  sizes={sizes} aifill={aifills} seeds={seeds}")
    print(f"  endturn={args.endturn} saveturns={args.saveturns} "
          f"-> up to {len(range(args.saveturns, args.endturn + 1, args.saveturns))} snapshots/game")
    print(f"  expected early(<=60)/mid(<=140)/late(>140) boards per game: "
          f"{sum(1 for t in range(args.saveturns, args.endturn+1, args.saveturns) if t <= 60)}"
          f"/{sum(1 for t in range(args.saveturns, args.endturn+1, args.saveturns) if 60 < t <= 140)}"
          f"/{sum(1 for t in range(args.saveturns, args.endturn+1, args.saveturns) if t > 140)}")


if __name__ == "__main__":
    main()
